(()=>{'use strict';
const S=window.SafeTrackSeed;
if(!S)return;
const PRODUCT_VERSION='SafeTrack v0.24';
const L=S.langs,K='safetrack-static-v6';
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],cp=x=>structuredClone(x);
const E=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let z;try{z=JSON.parse(localStorage.getItem(K)||'null')}catch{}
let C=z?.catalog||cp(S.trainings),R=z?.records||[];
let U={page:'dashboard',lang:'de',menu:0,emp:'',empSearch:'',f:{s:'',c:'',r:'',a:'active'},m:null},H=[];
localStorage.setItem('st-lang','de');
const N={de:'Deutsch',pl:'Polski',ru:'Русский',ar:'العربية',tr:'Türkçe',hu:'Magyar',ro:'Română'};
const d0=()=>new Date(new Date().setHours(0,0,0,0)),iso=n=>new Date(d0().getTime()+n*864e5).toISOString().slice(0,10),df=x=>Math.round((new Date(x+'T12:00')-d0())/864e5),fmt=x=>new Intl.DateTimeFormat('de-DE',{dateStyle:'medium'}).format(new Date(x+'T12:00'));
const todayLabel=()=>new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date());
const number=n=>`ST-UW-${String(n).padStart(3,'0')}`;
const numberValue=x=>{const m=String(x||'').match(/^ST-UW-(\d{3,})$/);return m?Number(m[1]):0};
function ensureTrainingNumbers(){const seedById=new Map(S.trainings.map(t=>[t.id,t.trainingNumber]));const used=new Set();let next=Math.max(0,...C.map(t=>numberValue(t.trainingNumber)),...S.trainings.map(t=>numberValue(t.trainingNumber)))+1;C.forEach(t=>{let candidate=t.trainingNumber||seedById.get(t.id)||'';if(!candidate||used.has(candidate)){while(used.has(number(next)))next++;candidate=number(next++)}t.trainingNumber=candidate;used.add(candidate)})}
function nextTrainingNumber(){const used=new Set(C.map(t=>t.trainingNumber));let n=Math.max(0,...C.map(t=>numberValue(t.trainingNumber)))+1;while(used.has(number(n)))n++;return number(n)}
ensureTrainingNumbers();
const snap=()=>({page:U.page,lang:'de',menu:0,emp:U.emp,empSearch:U.empSearch,f:cp(U.f),m:U.m?cp(U.m):null}),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
function push(){const s=snap();if(!H.length||!same(H.at(-1),s))H.push(s);if(H.length>30)H.shift()}
function restore(s){U.page=s.page;U.lang='de';U.menu=0;U.emp=s.emp;U.empSearch=s.empSearch||'';U.f=s.f;U.m=s.m;render()}
function back(){const s=H.pop();if(s)return restore(s);if(U.m){U.m=null;return render()}if(U.page!=='dashboard'){U.page='dashboard';U.menu=0;return render()}}
function save(){localStorage.setItem(K,JSON.stringify({catalog:C,records:R}))}
save();
function cn(x){return S.categories[x]?.de||x}
function rn(x){return S.roles[x]?.de||x}
function req(e,t){return t.active!==false&&t.roles.some(r=>r==='all'||r===e[4])}
function ass(e,n){return C.filter(t=>req(e,t)).map((t,i)=>{let r=R.find(x=>x.employeeId===e[1]&&x.trainingId===t.id),v=r?iso(t.months*30):iso([-18,-4,2,4,9,17,28,48,75,110,160,240][(n*7+i*5)%12]);return{t,d:v,r}})}
function st(a){let n=df(a.d);return n<=5?'critical':n<=30?'soon':'valid'}
function es(e,i){let a=ass(e,i).map(st);return a.includes('critical')?'critical':a.includes('soon')?'soon':'valid'}
function badge(s){return`<span class="badge ${s==='critical'?'red':s==='soon'?'amber':'green'}">${s==='critical'?'Kritisch':s==='soon'?'6–30 Tage':'Gültig'}</span>`}
function backButton(cls='btn st-back-button'){return(H.length||U.page!=='dashboard'||U.m)?`<button class="${cls}" data-a="back">Zurück</button>`:''}
function pageTitle(){return U.page==='dashboard'?'Übersicht':U.page==='employees'?'Mitarbeitende':U.page==='trainings'?'Unterweisungen':U.page==='documents-v024'?'Dokumente':'Nachweise'}
function frame(x){document.documentElement.lang='de';document.documentElement.dir='ltr';return`<div class="app"><aside class="sidebar ${U.menu?'open':''}"><div class="brand"><div class="brand-mark">ST</div><div><h1>SafeTrack</h1><small>Unterweisungsmanagement</small></div></div><nav class="nav">${[['dashboard','Übersicht'],['employees','Mitarbeitende'],['trainings','Unterweisungen']].map(a=>`<button data-page="${a[0]}" class="${U.page===a[0]?'active':''}">${a[1]}</button>`).join('')}</nav><div class="sidebar-foot">${C.length} Unterweisungen <span class="st-menu-version" aria-label="Aktuelle Version ${PRODUCT_VERSION}">${PRODUCT_VERSION}</span></div></aside><main class="main"><header class="topbar"><div class="toolbar"><button class="btn menu" data-a="menu">Menü</button>${backButton()}<h2>${pageTitle()}</h2></div><div class="top-actions"><div class="avatar">MK</div></div></header><div class="content">${x}</div></main></div>${modal()}<div class="toast" id="toast"></div>`}
function all(){return S.employees.flatMap((e,i)=>ass(e,i).map(a=>({...a,e,i,s:st(a)})))}
function kpi(s,c,h,p,a,n,t){return`<button class="card kpi ${c}" data-a="status" data-s="${s}" aria-label="${h}"><div class="kpi-top"><b><span class="st-kpi-state-icon ${s}" aria-hidden="true"></span>${h}</b><span>${p}</span></div><div class="kpi dual"><div><strong>${a}/${t}</strong><span>Unterweisungen</span></div><i></i><div><strong>${n}/${S.employees.length}</strong><span>Mitarbeitende</span></div></div></button>`}
function dashboard(){let a=all(),g={critical:a.filter(x=>x.s==='critical'),soon:a.filter(x=>x.s==='soon'),valid:a.filter(x=>x.s==='valid')},p={};['critical','soon','valid'].forEach(s=>p[s]=S.employees.filter((e,i)=>es(e,i)===s));let dep=[...new Set(S.employees.map(e=>e[2]))],next=[...a].sort((x,y)=>x.d.localeCompare(y.d)).slice(0,6);return`<section class="card hero"><div><span class="muted">HEUTE · ${todayLabel()}</span><h3>Guten Tag, Maria.</h3><p>Fällige Unterweisungen und aktuelle Nachweise.</p></div></section><section class="kpis">${kpi('critical','danger','Kritisch','Abgelaufen oder in höchstens 5 Tagen fällig',g.critical.length,p.critical.length,a.length)}${kpi('soon','warning','In 6–30 Tagen fällig','Planbare Fristen',g.soon.length,p.soon.length,a.length)}${kpi('valid','success','Gültig','Aktuelle Unterweisungen',g.valid.length,p.valid.length,a.length)}</section><section class="grid2"><div class="card panel"><h3>Vollständig aktuell nach Bereich</h3>${dep.map(d=>{let x=S.employees.map((e,i)=>({e,i})).filter(x=>x.e[2]===d),n=x.filter(x=>es(x.e,x.i)==='valid').length,v=Math.round(n/x.length*100);return`<div class="progress-row"><b>${E(d)}</b><div class="track"><div class="bar" style="width:${v}%"></div></div><span>${v}%</span></div>`).join('')}</div><div class="card panel"><h3>Nächste Fristen</h3><div class="deadline">${next.map(x=>`<button data-a="employee" data-id="${x.e[1]}"><b>${E(x.e[0])}</b><br><small>${E(x.t.trainingNumber)} · ${E(x.t.title.de)} · ${fmt(x.d)}</small></button>`).join('')}</div></div></section>`}
function employees(){let a=S.employees.map((e,i)=>({e,i,s:es(e,i)})).filter(x=>!U.emp||x.s===U.emp);return`<section class="card table-card"><div class="table-toolbar toolbar st-employee-toolbar"><label class="st-employee-search"><span>Mitarbeitende suchen</span><input id="employee-search" type="search" value="${E(U.empSearch)}" placeholder="Name oder PNr." autocomplete="off"></label><select id="emp"><option value="">Alle Status</option><option value="critical" ${U.emp==='critical'?'selected':''}>Kritisch</option><option value="soon" ${U.emp==='soon'?'selected':''}>6–30 Tage</option><option value="valid" ${U.emp==='valid'?'selected':''}>Gültig</option></select><button class="btn" data-a="clear">Filter löschen</button></div><table><thead><tr><th>Name</th><th>Bereich</th><th>Tätigkeit</th><th>Status</th><th></th></tr></thead><tbody>${a.map(x=>`<tr><td data-label="Name"><button class="employee-link" data-a="employee" data-id="${x.e[1]}"><span>${E(x.e[0])}</span><small>${E(x.e[1])}</small></button></td><td data-label="Bereich">${E(x.e[2])}</td><td data-label="Tätigkeit">${E(x.e[3])}</td><td>${badge(x.s)}</td><td><button class="btn small" data-a="employee" data-id="${x.e[1]}">Details</button></td></tr>`).join('')}</tbody></table></section>`}
function card(t){return`<article class="card training ${t.active===false?'inactive':''}"><div class="training-top"><div><span class="st-training-number">${E(t.trainingNumber)}</span><h4>${E(t.title.de)}</h4><p>${E(t.description.de)}</p></div><div class="code">${E(t.icon)}</div></div><div class="meta"><span class="badge">${E(t.trainingNumber)}</span><span class="badge">v${E(t.version)}</span><span class="badge">${t.months} Monate</span>${t.questions&&Object.keys(t.questions).length?'<span class="badge">Wissensfragen</span>':''}</div><div class="roles">${t.roles.slice(0,5).map(r=>`<span>${E(rn(r))}</span>`).join('')}</div><div class="actions"><button class="btn small" data-a="edit" data-id="${t.id}">Bearbeiten</button><button class="btn small" data-a="copy" data-id="${t.id}">Duplizieren</button><button class="btn primary small" data-a="start" data-id="${t.id}" ${t.active===false?'disabled':''}>Starten</button></div></article>`}
function trainings(){let f=U.f,a=C.filter(t=>(!f.s||(`${t.trainingNumber} ${t.id} ${t.title.de}`).toLowerCase().includes(f.s.toLowerCase()))&&(!f.c||t.category===f.c)&&(!f.r||t.roles.includes('all')||t.roles.includes(f.r))&&(!f.a||(f.a==='active'?t.active!==false:t.active===false))),g=Object.keys(S.categories).map(c=>[c,a.filter(t=>t.category===c)]).filter(x=>x[1].length);return`<section class="card"><div class="section-head"><div><h3>Unterweisungskatalog</h3><p class="muted">${a.length}/${C.length} Unterweisungen</p></div><div class="actions"><button class="btn" data-a="export">JSON exportieren</button><button class="btn" data-a="import">JSON importieren</button><button class="btn" data-a="reset">Testdaten zurücksetzen</button><button class="btn primary" data-a="edit">Hinzufügen</button><input id="file" type="file" accept="application/json" hidden></div></div><div class="panel"><div class="filters"><input id="fs" value="${E(f.s)}" placeholder="ID oder Titel suchen"><select id="fc"><option value="">Alle Kategorien</option>${Object.keys(S.categories).map(c=>`<option value="${c}" ${f.c===c?'selected':''}>${E(cn(c))}</option>`).join('')}</select><select id="fr"><option value="">Alle Tätigkeiten</option>${Object.keys(S.roles).filter(r=>r!=='all').map(r=>`<option value="${r}" ${f.r===r?'selected':''}>${E(rn(r))}</option>`).join('')}</select><select id="fa"><option value="active">Aktiv</option><option value="archived" ${f.a==='archived'?'selected':''}>Archiviert</option><option value="">Alle</option></select></div></div></section>${g.map(x=>`<section class="group"><div class="group-title"><h3>${E(cn(x[0]))}</h3><span class="count">${x[1].length}</span></div><div class="training-grid">${x[1].map(card).join('')}</div></section>`).join('')}`}
function records(){return`<section class="card panel"><h3>Nachweise</h3>${R.length?R.map(r=>{const t=C.find(x=>x.id===r.trainingId);return`<div class="training-row"><div><b>${E(r.employeeName)}</b><br><small>${E(r.trainingNumber||t?.trainingNumber||r.trainingId)} · ${E(t?.title.de||r.trainingId)} · ${fmt(r.date)} · ${E(r.instructor)}</small></div>${badge('valid')}</div>`}).join(''):'<div class="empty">Keine Nachweise</div>'}</section>`}
function modal(){if(!U.m)return'';if(U.m.t==='emp')return empModal();if(U.m.t==='edit')return editModal();return sessionModal()}
function empModal(){let i=S.employees.findIndex(e=>e[1]===U.m.id),e=S.employees[i],a=ass(e,i);return`<div class="modal-bg"><div class="modal"><div class="modal-head">${backButton('btn small st-modal-back')}<div><h3>${E(e[0])}</h3><span>${E(e[1])} · ${E(e[2])} · ${E(e[3])}</span></div><button class="close" data-a="close">Schließen</button></div><div class="modal-body"><div class="employee-head">${badge(es(e,i))}<button class="btn primary" data-a="sessionEmp" data-id="${e[1]}">Unterweisung starten</button></div><div class="training-list">${a.map(x=>`<div class="training-row"><div><span class="st-training-number">${E(x.t.trainingNumber)}</span><b>${E(x.t.title.de)}</b><br><small>${fmt(x.d)} · v${x.t.version}</small></div>${badge(st(x))}</div>`).join('')}</div></div></div></div>`}
function editModal(){let id=U.m.id,t=id?C.find(x=>x.id===id):{id:'',trainingNumber:nextTrainingNumber(),icon:'NE',category:'general',roles:[],version:'1.0',months:12,active:true,title:{},description:{},slides:{},questions:{},custom:true};return`<div class="modal-bg"><div class="modal"><div class="modal-head">${backButton('btn small st-modal-back')}<h3>${id?'Unterweisung bearbeiten':'Unterweisung hinzufügen'}</h3><button class="close" data-a="close">Schließen</button></div><div class="modal-body"><div class="form-grid"><div class="field"><label>Unterweisungs-ID</label><input id="enumber" value="${E(t.trainingNumber)}" readonly></div><div class="field"><label>Code</label><input id="ei" value="${E(t.icon)}"></div><div class="field"><label>Version</label><input id="ev" value="${E(t.version)}"></div><div class="field"><label>Kategorie</label><select id="ec">${Object.keys(S.categories).map(c=>`<option value="${c}" ${t.category===c?'selected':''}>${E(cn(c))}</option>`).join('')}</select></div><div class="field"><label>Wiederholung (Monate)</label><input id="em" type="number" min="1" value="${t.months}"></div><label><input id="ea" type="checkbox" ${t.active!==false?'checked':''}> Aktiv</label></div><h4>Zugeordnete Tätigkeiten</h4><div class="role-grid">${Object.keys(S.roles).map(r=>`<label><input class="er" type="checkbox" value="${r}" ${t.roles.includes(r)?'checked':''}> ${E(rn(r))}</label>`).join('')}</div><h4>Sprachfassungen</h4>${L.map(l=>`<details class="lang-block" ${l==='de'?'open':''}><summary>${N[l]}</summary><div class="field"><label>Titel</label><input id="et-${l}" value="${E(t.title[l]||'')}"><label>Beschreibung</label><textarea id="ed-${l}" rows="3">${E(t.description[l]||'')}</textarea></div></details>`).join('')}</div><div class="modal-foot">${id?`<button class="btn" data-a="toggle" data-id="${id}">${t.active===false?'Aktivieren':'Archivieren'}</button><button class="btn danger" data-a="delete" data-id="${id}">Löschen</button>`:''}<button class="btn" data-a="close">Abbrechen</button><button class="btn primary" data-a="save" data-id="${id||''}">Speichern</button></div></div></div>`}
function sessionModal(){let e=S.employees.find(x=>x[1]===U.m.e)||S.employees[0],t=C.find(x=>x.id===U.m.id)||C.find(x=>req(e,x)),l=e[5],sl=t.slides[l]||t.slides.de,qq=t.questions?.[l]||[];return`<div class="modal-bg"><div class="modal"><div class="modal-head">${backButton('btn small st-modal-back')}<div><span class="st-training-number">${E(t.trainingNumber)}</span><h3>${E(t.title[l]||t.title.de)}</h3><span>${E(e[0])} · ${N[l]}</span></div><button class="close" data-a="close">Schließen</button></div><div class="modal-body"><div class="field"><label>Unterweisende Person</label><input id="instr" value="Maria Keller"></div><div class="session-columns"><section class="session-card" dir="${l==='ar'?'rtl':'ltr'}"><span class="st-training-number">${E(t.trainingNumber)}</span><h4>${E(t.title[l]||t.title.de)}</h4>${sl.map(s=>`<h5>${E(s[0])}</h5><ul>${s[1].map(x=>`<li>${E(x)}</li>`).join('')}</ul>`).join('')}${qq.map((x,i)=>`<div class="quiz"><b>${E(x.q)}</b>${x.o.map((o,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${E(o)}</label>`).join('')}</div>`).join('')}<label><input id="ok" type="checkbox"> Ich bestätige, dass ich die Unterweisung erhalten und verstanden habe.</label></section>${l!=='de'?`<section class="session-card" dir="ltr"><span class="badge">Deutsche Referenz für die unterweisende Person</span><span class="st-training-number">${E(t.trainingNumber)}</span><h4>${E(t.title.de)}</h4>${t.slides.de.map(s=>`<h5>${E(s[0])}</h5><ul>${s[1].map(x=>`<li>${E(x)}</li>`).join('')}</ul>`).join('')}</section>`:''}</div><h4>Unterschrift</h4><canvas id="sig" class="signature"></canvas></div><div class="modal-foot"><button class="btn" data-a="clearSig">Löschen</button><button class="btn primary" data-a="saveSession" data-e="${e[1]}" data-id="${t.id}">Speichern</button></div></div></div>`}
function render(){U.lang='de';let x=U.page==='dashboard'?dashboard():U.page==='employees'?employees():U.page==='trainings'?trainings():records();q('#app').innerHTML=frame(x);bind();syncProductVersion();if(U.m?.t==='session')requestAnimationFrame(pad);requestAnimationFrame(enhanceShell)}
function bind(){qa('[data-page]').forEach(b=>b.onclick=()=>{if(U.page!==b.dataset.page||U.m)push();U.page=b.dataset.page;U.m=null;U.menu=0;render()});qa('[data-a]').forEach(b=>b.onclick=()=>act(b));q('#emp')?.addEventListener('change',e=>{U.emp=e.target.value;render()});q('#employee-search')?.addEventListener('input',e=>{U.empSearch=e.target.value;window.__SafeTrackEmployeeGroups?.refreshEmployees?.()});[['#fs','s','input'],['#fc','c','change'],['#fr','r','change'],['#fa','a','change']].forEach(x=>q(x[0])?.addEventListener(x[2],e=>{U.f[x[1]]=e.target.value;render()}));q('#file')?.addEventListener('change',e=>imp(e.target.files[0]))}
function openEmployee(id){push();U.m={t:'emp',id};render()}
function act(b){let a=b.dataset.a,id=b.dataset.id;if(a==='menu'){U.menu=!U.menu;render()}if(a==='back')return back();if(a==='status'){push();U.emp=b.dataset.s;U.empSearch='';U.page='employees';U.m=null;render()}if(a==='clear'){U.emp='';U.empSearch='';render()}if(a==='employee')openEmployee(id);if(a==='close'){U.m=null;render()}if(a==='edit'){push();U.m={t:'edit',id:id||''};render()}if(a==='copy'){let x=cp(C.find(t=>t.id===id));x.id='copy-'+Date.now();x.trainingNumber=nextTrainingNumber();x.custom=true;L.forEach(l=>x.title[l]+=' – Kopie');C.push(x);save();push();U.m={t:'edit',id:x.id};render()}if(a==='toggle'){let x=C.find(t=>t.id===id);x.active=!x.active;save();U.m=null;render()}if(a==='delete'){let x=C.find(t=>t.id===id);if(x.custom&&!R.some(r=>r.trainingId===id))C=C.filter(t=>t.id!==id);else x.active=false;save();U.m=null;render()}if(a==='save')saveTraining(id);if(a==='export')exp();if(a==='import')q('#file').click();if(a==='reset'&&confirm('Testdaten zurücksetzen?')){C=cp(S.trainings);ensureTrainingNumbers();R=[];save();render()}if(a==='start'){push();let e=S.employees.find(x=>req(x,C.find(t=>t.id===id)))||S.employees[0];U.m={t:'session',e:e[1],id};render()}if(a==='session'||a==='sessionEmp'){push();let e=id?S.employees.find(x=>x[1]===id):S.employees[0],t=C.find(x=>req(e,x));U.m={t:'session',e:e[1],id:t.id};render()}if(a==='clearSig'){P?.clearRect(0,0,P.canvas.width,P.canvas.height);signed=0}if(a==='saveSession')finish(b.dataset.e,id)}
function saveTraining(id){let x=id?C.find(t=>t.id===id):{id:'custom-'+Date.now(),trainingNumber:q('#enumber')?.value||nextTrainingNumber(),custom:true,title:{},description:{},slides:{},questions:{}};x.trainingNumber=x.trainingNumber||q('#enumber')?.value||nextTrainingNumber();x.icon=q('#ei').value.trim().toUpperCase().slice(0,3)||'NE';x.version=q('#ev').value||'1.0';x.category=q('#ec').value;x.months=Math.max(1,+q('#em').value||12);x.active=q('#ea').checked;x.roles=qa('.er:checked').map(x=>x.value);if(!x.roles.length)x.roles=['all'];L.forEach(l=>{x.title[l]=q('#et-'+l).value.trim()||x.title.de||'Neue Unterweisung';x.description[l]=q('#ed-'+l).value.trim()||x.description.de||'';x.slides[l]=x.slides[l]?.length?x.slides[l]:[[x.title[l],[x.description[l],'Betriebliche Anweisung beachten','Bei Unsicherheit nachfragen']]]});if(!id)C.push(x);ensureTrainingNumbers();save();U.m=null;render()}
function exp(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({catalog:C,records:R},null,2)],{type:'application/json'}));a.download='safetrack-backup.json';a.click()}
function imp(f){if(!f)return;let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);if(!Array.isArray(d.catalog))throw Error('Ungültige Datei');C=d.catalog;R=d.records||[];ensureTrainingNumbers();save();render()}catch(e){toast(e.message)}};r.readAsText(f)}
let P,draw=0,signed=0;
function pad(){let c=q('#sig');if(!c)return;let r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;P=c.getContext('2d');P.scale(d,d);P.lineWidth=2;P.lineCap='round';let p=e=>({x:e.clientX-r.left,y:e.clientY-r.top});c.onpointerdown=e=>{draw=1;signed=1;let x=p(e);P.beginPath();P.moveTo(x.x,x.y)};c.onpointermove=e=>{if(!draw)return;let x=p(e);P.lineTo(x.x,x.y);P.stroke()};c.onpointerup=c.onpointercancel=()=>draw=0}
function finish(eid,id){let e=S.employees.find(x=>x[1]===eid),t=C.find(x=>x.id===id),qq=t.questions?.[e[5]]||[];if(!q('#ok').checked||!signed)return toast('Bestätigung und Unterschrift erforderlich');for(let i=0;i<qq.length;i++){let v=q(`input[name=q${i}]:checked`);if(!v||+v.value!==qq[i].a)return toast('Antwort bitte korrigieren')}R.unshift({id:'R-'+Date.now(),employeeId:eid,employeeName:e[0],trainingId:id,trainingNumber:t.trainingNumber,date:iso(0),instructor:q('#instr').value||'Maria Keller'});save();U.m=null;U.page='records';render()}
function toast(x){let e=q('#toast');if(!e)return;e.textContent=x;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
const HEADER_SELECTORS=['.modal-head','.st-group-dialog-head','.st-print-options-head','.st-print-preview-toolbar','.st-group-preview-toolbar','.st-v020-detail>header','.st-v020-registry>header','.st-v023-assembled>header','.st-v024-detail-head','.st-v024-compare-head','.st-v024-signed>header'];
function hasBack(h){return[...h.querySelectorAll('button')].some(b=>/^(Zurück|Schließen)$/i.test(b.textContent.trim())||b.matches('.st-back-button,.st-modal-back'))}
function hasMenu(h){return[...h.querySelectorAll('button')].some(b=>/^Menü$/i.test(b.textContent.trim())||b.matches('[data-core-global-menu]'))}
function enhanceHeaders(){for(const selector of HEADER_SELECTORS)document.querySelectorAll(selector).forEach(h=>{if(!hasBack(h)||hasMenu(h))return;const b=document.createElement('button');b.type='button';b.className='btn st-ui-menu-button';b.dataset.coreGlobalMenu='1';b.textContent='Menü';const back=[...h.querySelectorAll('button')].find(x=>/^(Zurück|Schließen)$/i.test(x.textContent.trim())||x.matches('.st-back-button,.st-modal-back'));if(back&&back.parentNode===h)h.insertBefore(b,back);else h.appendChild(b)})}
function openMenu(){document.querySelectorAll('.modal-bg,.st-group-dialog-bg,.st-group-confirmation-preview-bg,.st-print-options-bg,.st-print-preview-bg,.st-v020-detail-bg,.st-v023-registry-bg,.st-v023-assembled-bg,.st-v024-signed-bg').forEach(x=>x.remove());if(window.__SafeTrack?.state)window.__SafeTrack.state.m=null;const menu=document.querySelector('.topbar [data-a="menu"]');if(menu){menu.click();return}document.querySelector('.sidebar')?.classList.add('open')}
function syncProductVersion(){document.title=document.title.replace(/SafeTrack v0\.\d+/,PRODUCT_VERSION);document.querySelectorAll('body>.st-version-badge').forEach(x=>x.remove());document.querySelectorAll('.st-menu-version').forEach(x=>{x.textContent=PRODUCT_VERSION;x.setAttribute('aria-label',`Aktuelle Version ${PRODUCT_VERSION}`)});document.querySelectorAll('.st-print-footer span:first-child').forEach(x=>x.textContent=PRODUCT_VERSION);if(window.__SafeTrack)window.__SafeTrack.version=PRODUCT_VERSION}
let shellQueued=false;function enhanceShell(){if(shellQueued)return;shellQueued=true;requestAnimationFrame(()=>{shellQueued=false;syncProductVersion();enhanceHeaders()})}
document.addEventListener('click',e=>{const b=e.target.closest?.('[data-core-global-menu]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();openMenu()},true);
new MutationObserver(enhanceShell).observe(document.documentElement,{childList:true,subtree:true});
let lastDate=todayLabel();setInterval(()=>{const d=todayLabel();if(d===lastDate)return;lastDate=d;const el=document.querySelector('.hero .muted');if(el)el.textContent=`HEUTE · ${d}`},30000);
function runtimeAudit(){const srcs=[...document.scripts].map(s=>s.getAttribute('src')||'');const forbidden=['app-v016.js','safetrack-v023-dashboard-fix.js','safetrack-v023-hierarchy-nav-fix.js'],violations=forbidden.filter(name=>srcs.some(src=>src.includes(name)));window.__SafeTrackRuntimeAudit={owner:'core.js',productVersion:PRODUCT_VERSION,violations};if(violations.length)console.error('SafeTrack runtime ownership violation',violations)}
window.addEventListener('load',runtimeAudit,{once:true});
render();
const apiObject={get catalog(){return C},get records(){return R},state:U,render,back,pushHistory:push,openEmployee,nextTrainingNumber,ensureTrainingNumbers,productVersion:PRODUCT_VERSION};Object.defineProperty(apiObject,'version',{enumerable:true,configurable:false,get:()=>PRODUCT_VERSION,set:()=>{}});window.__SafeTrack=apiObject;
syncProductVersion();enhanceShell();
})();