(()=>{'use strict';
const seed=window.SafeTrackSeed,api=window.__SafeTrack;
if(!seed||!api)return;
const K='safetrack-static-v6',OFF=[-18,-4,2,4,9,17,28,48,75,110,160,240],RANK={critical:0,soon:1,valid:2},LABEL={critical:'Kritisch',soon:'In 6–30 Tagen fällig',valid:'Gültig'},AREA_ORDER=window.__SafeTrackV017?.areas||['Produktion','Reinigung','Logistik','Instandhaltung','Qualitätskontrolle'];
const LANG={de:'Deutsch',pl:'Polski',ru:'Русский',ar:'العربية',tr:'Türkçe',hu:'Magyar',ro:'Română'};
const CONF={de:['Bestätigung der Unterweisung','Ich bestätige, dass ich diese Unterweisung erhalten, verstanden und Gelegenheit für Rückfragen hatte.'],pl:['Potwierdzenie instruktażu','Potwierdzam, że odbyłem(-am) ten instruktaż, zrozumiałem(-am) jego treść i miałem(-am) możliwość zadawania pytań.'],ru:['Подтверждение инструктажа','Я подтверждаю, что прошёл(прошла) этот инструктаж, понял(а) его содержание и имел(а) возможность задать вопросы.'],ar:['تأكيد التدريب','أؤكد أنني تلقيت هذا التدريب وفهمت محتواه وأتيحت لي فرصة طرح الأسئلة.'],tr:['Eğitim onayı','Bu eğitimi aldığımı, içeriğini anladığımı ve soru sorma fırsatı bulduğumu onaylıyorum.'],hu:['Az oktatás megerősítése','Igazolom, hogy az oktatást megkaptam, megértettem, és lehetőségem volt kérdéseket feltenni.'],ro:['Confirmarea instruirii','Confirm că am primit această instruire, am înțeles conținutul și am avut posibilitatea să adresez întrebări.']};
let currentEmployeeId='',selected=new Set(),batch=null,printContext=null,printCleanupTimer=0;
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normalize=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const day=()=>new Date(new Date().setHours(0,0,0,0)),add=n=>new Date(day().getTime()+n*864e5).toISOString().slice(0,10),cls=n=>n<=5?'critical':n<=30?'soon':'valid';
const req=(e,t)=>t.active!==false&&Array.isArray(t.roles)&&t.roles.some(r=>r==='all'||r===e[4]);
const cn=(c,l='de')=>seed.categories?.[c]?.[l]||seed.categories?.[c]?.de||c;
const tn=(t,l='de')=>t.title?.[l]||t.title?.de||t.id;
const fmt=(v,l='de-DE')=>v?new Intl.DateTimeFormat(l,{dateStyle:'medium'}).format(new Date(v+'T12:00:00')):'';
function records(){try{return JSON.parse(localStorage.getItem(K)||'null')?.records||[]}catch{return[]}}
function assignments(id){const i=seed.employees.findIndex(e=>e[1]===id),e=seed.employees[i];if(!e)return[];const rs=records();return api.catalog.filter(t=>req(e,t)).map((t,j)=>{const record=rs.find(r=>r.employeeId===e[1]&&r.trainingId===t.id),dueDays=record?t.months*30:OFF[(i*7+j*5)%OFF.length];return{training:t,dueDays,dueDate:add(dueDays),status:cls(dueDays),record}})}
function overall(id){const s=assignments(id).map(x=>x.status);return s.includes('critical')?'critical':s.includes('soon')?'soon':'valid'}
function groupsFor(id){const m=new Map();assignments(id).forEach(x=>{const c=x.training.category;if(!m.has(c))m.set(c,[]);m.get(c).push(x)});return[...m.entries()].map(([category,items])=>{items.sort((a,b)=>RANK[a.status]-RANK[b.status]||a.dueDays-b.dueDays||tn(a.training).localeCompare(tn(b.training),'de'));const counts={critical:0,soon:0,valid:0};items.forEach(x=>counts[x.status]++);return{category,name:cn(category),status:items.reduce((w,x)=>RANK[x.status]<RANK[w]?x.status:w,'valid'),counts,earliestDue:Math.min(...items.map(x=>x.dueDays)),items}}).sort((a,b)=>RANK[a.status]-RANK[b.status]||a.earliestDue-b.earliestDue||a.name.localeCompare(b.name,'de'))}
const badge=s=>`<span class="st-category-status st-${s}"><span class="st-status-icon"></span>${LABEL[s]}</span>`;
function matchesEmployee(e,query){if(!query)return true;return normalize(`${e[0]} ${e[1]}`).includes(normalize(query))}
function employeeJobGroups(){const f=api.state.emp||'',query=api.state.empSearch||'',m=new Map();seed.employees.map(e=>({employee:e,status:overall(e[1])})).filter(x=>(!f||x.status===f)&&matchesEmployee(x.employee,query)).forEach(x=>{const job=x.employee[3]||'Ohne Tätigkeit';if(!m.has(job))m.set(job,[]);m.get(job).push(x)});return[...m.entries()].map(([job,people])=>{people.sort((a,b)=>a.employee[0].localeCompare(b.employee[0],'de'));const counts={critical:0,soon:0,valid:0};people.forEach(p=>counts[p.status]++);return{job,area:people[0]?.employee?.[2]||'Sonstige',people,counts,worst:people.reduce((w,p)=>RANK[p.status]<RANK[w]?p.status:w,'valid')}}).sort((a,b)=>a.job.localeCompare(b.job,'de'))}
function employeeAreaGroups(){const m=new Map(AREA_ORDER.map(a=>[a,[]]));employeeJobGroups().forEach(g=>{if(!m.has(g.area))m.set(g.area,[]);m.get(g.area).push(g)});return[...m.entries()].filter(([,jobs])=>jobs.length).map(([area,jobs])=>{jobs.sort((a,b)=>a.job.localeCompare(b.job,'de'));const people=jobs.flatMap(j=>j.people),counts={critical:0,soon:0,valid:0};people.forEach(p=>counts[p.status]++);return{area,jobs,people,counts,worst:people.reduce((w,p)=>RANK[p.status]<RANK[w]?p.status:w,'valid')}})}
function employeeRow({employee,status}){return`<button type="button" class="st-employee-row" data-st-employee="${E(employee[1])}"><span class="st-employee-copy"><strong>${E(employee[0])}</strong><small>${E(employee[3])}</small></span><span class="st-employee-pnr-column"><span>PNr.</span><strong class="st-pnr-value">${E(employee[1])}</strong></span>${badge(status)}</button>`}
function jobMarkup(g,areaIndex,jobIndex,expanded){const id=`st-area-${areaIndex}-job-${jobIndex}-body`;return`<section class="st-job-group" data-job="${E(g.job)}"><button type="button" class="st-job-toggle" data-st-action="toggle-job" data-employee-action="toggle-job" aria-expanded="${expanded?'true':'false'}" aria-controls="${id}"><span class="st-job-title"><strong>${E(g.job)}</strong><small>${g.people.length} Mitarbeitende</small></span><span class="st-job-summary">${badge(g.worst)}<span>${g.counts.critical} kritisch · ${g.counts.soon} fällig · ${g.counts.valid} gültig</span><span class="st-chevron"></span></span></button><div class="st-job-body" id="${id}" ${expanded?'':'hidden'}><div class="st-employee-column-head"><span>Mitarbeitende Person</span><span>PNr.</span><span>Status</span></div>${g.people.map(employeeRow).join('')}</div></section>`}
function areaMarkup(g,i,expanded){const id=`st-area-${i}-body`;return`<section class="st-area-group" data-area="${E(g.area)}"><button type="button" class="st-area-toggle" data-st-action="toggle-area" data-employee-action="toggle-area" aria-expanded="${expanded?'true':'false'}" aria-controls="${id}"><span class="st-area-title"><strong>${E(g.area)}</strong><small>${g.people.length} Mitarbeitende · ${g.jobs.length} Tätigkeiten</small></span><span class="st-area-summary">${badge(g.worst)}<span>${g.counts.critical} kritisch · ${g.counts.soon} fällig · ${g.counts.valid} gültig</span><span class="st-chevron"></span></span></button><div class="st-area-body" id="${id}" ${expanded?'':'hidden'}>${g.jobs.map((j,n)=>jobMarkup(j,i,n,expanded)).join('')}</div></section>`}
function hierarchyMarkup(){const query=api.state.empSearch||'',gs=employeeAreaGroups(),expanded=Boolean(query.trim());return gs.length?gs.map((g,i)=>areaMarkup(g,i,expanded)).join(''):`<div class="empty">${query?`Keine Mitarbeitenden für „${E(query)}“ gefunden.`:'Keine Mitarbeitenden für diesen Status.'}</div>`}
function renderPage(){return`<section class="card table-card" data-employees-owner="employees.js"><div class="table-toolbar toolbar st-employee-toolbar"><label class="st-employee-search"><span>Mitarbeitende suchen</span><input id="employee-search" type="search" value="${E(api.state.empSearch||'')}" placeholder="Name oder PNr." autocomplete="off"></label><select id="emp"><option value="">Alle Status</option><option value="critical" ${api.state.emp==='critical'?'selected':''}>Kritisch</option><option value="soon" ${api.state.emp==='soon'?'selected':''}>6–30 Tage</option><option value="valid" ${api.state.emp==='valid'?'selected':''}>Gültig</option></select><button class="btn" data-employee-action="clear-filters">Filter löschen</button></div><div class="st-job-groups st-area-groups">${hierarchyMarkup()}</div></section>`}
function refreshEmployees(){const host=document.querySelector('.st-job-groups');if(host)host.innerHTML=hierarchyMarkup()}
function ensureEmployeeContext(id){if(currentEmployeeId!==id){currentEmployeeId=id;selected=new Set();batch=null}}
function idsFor(c){const g=[...document.querySelectorAll('.st-category-group')].find(x=>x.dataset.category===c);return g?[...g.querySelectorAll('[data-st-training]')].map(x=>x.dataset.stTraining):[]}
function sync(){document.querySelectorAll('[data-st-training]').forEach(x=>x.checked=selected.has(x.dataset.stTraining));document.querySelectorAll('[data-st-category]').forEach(x=>{const ids=idsFor(x.dataset.stCategory),n=ids.filter(id=>selected.has(id)).length;x.checked=ids.length>0&&n===ids.length;x.indeterminate=n>0&&n<ids.length;x.setAttribute('aria-checked',x.indeterminate?'mixed':String(x.checked))});document.querySelectorAll('[data-st-count]').forEach(x=>x.textContent=String(selected.size));document.querySelectorAll('[data-employee-action="print"],[data-employee-action="start"]').forEach(x=>x.disabled=!selected.size)}
function categoryMarkup(g,i){const id=`st-category-${i}-body`;return`<section class="st-category-group" data-category="${E(g.category)}" data-status="${g.status}"><div class="st-category-head"><label class="st-category-check"><input type="checkbox" data-st-category="${E(g.category)}"><span>${E(g.name)}</span></label><button type="button" class="st-category-toggle" data-st-action="toggle-category" data-employee-action="toggle-category" aria-expanded="false" aria-controls="${id}">${badge(g.status)}<span class="st-category-counts">${g.counts.critical} kritisch · ${g.counts.soon} fällig · ${g.counts.valid} gültig</span><span class="st-chevron"></span></button></div><div class="st-category-body" id="${id}" hidden>${g.items.map(x=>`<label class="st-training-choice" data-status="${x.status}"><input type="checkbox" data-st-training="${E(x.training.id)}" ${selected.has(x.training.id)?'checked':''}><span class="st-training-copy"><span class="st-training-number">${E(x.training.trainingNumber)}</span><strong>${E(tn(x.training))}</strong><small>v${E(x.training.version)} · ${fmt(x.dueDate)}</small></span>${badge(x.status)}</label>`).join('')}</div></section>`}
function renderProfile(id){const e=seed.employees.find(x=>x[1]===id);if(!e)return'';ensureEmployeeContext(id);const gs=groupsFor(id),all=gs.flatMap(g=>g.items);return`<div class="modal-bg"><div class="modal" data-employees-owner="employees.js"><div class="modal-head"><button class="btn small st-modal-back" data-a="back">Zurück</button><div><h3>${E(e[0])}</h3><span>${E(e[1])} · ${E(e[2])} · ${E(e[3])}</span></div><button class="close" data-a="close">Schließen</button></div><div class="modal-body"><div class="st-employee-actions"><div class="st-employee-status">${badge(overall(id))}<span>${all.length} zugeordnete Unterweisungen</span></div><div class="st-quick-actions"><button class="btn small" data-st-action="select-critical" data-employee-action="select-critical">Alle kritischen auswählen</button><button class="btn small" data-st-action="select-soon" data-employee-action="select-soon">Alle in 6–30 Tagen fälligen auswählen</button><button class="btn small" data-st-action="clear" data-employee-action="clear">Auswahl aufheben</button></div></div><div class="st-category-list">${gs.map(categoryMarkup).join('')}</div><div class="st-selection-bar"><strong><span data-st-count>${selected.size}</span> ausgewählt</strong><div class="st-selection-actions"><button class="btn" data-st-action="print" data-employee-action="print" ${selected.size?'':'disabled'}>Auswahl drucken</button><button class="btn primary" data-st-action="start" data-employee-action="start" ${selected.size?'':'disabled'}>Auswahl starten</button></div></div></div></div></div>`}
const selectedAssignments=()=>groupsFor(currentEmployeeId).flatMap(g=>g.items).filter(x=>selected.has(x.training.id));
function toast(s){const t=document.querySelector('#toast');if(!t)return;t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function startBatch(){const items=selectedAssignments();if(!items.length)return toast('Mindestens eine Unterweisung auswählen');api.pushHistory?.();batch={employeeId:currentEmployeeId,ids:items.map(x=>x.training.id),index:0};openBatch()}
function openBatch(){if(!batch||batch.index>=batch.ids.length){const id=batch?.employeeId||currentEmployeeId;batch=null;selected=new Set();api.state.page='employees';api.state.m={t:'emp',id};api.render();return}api.state.m={t:'session',e:batch.employeeId,id:batch.ids[batch.index]};api.render()}
const closePrint=()=>document.querySelector('.st-print-options-bg')?.remove();
function removeSystemPrintRoot(){document.querySelector('#st-system-print-root')?.remove()}
function closePrintPreview(){document.querySelector('.st-print-preview-bg')?.remove();printContext=null;removeSystemPrintRoot()}
function openPrintOptions(){if(!selectedAssignments().length)return toast('Mindestens eine Unterweisung auswählen');closePrint();const d=document.createElement('div');d.className='st-print-options-bg';d.innerHTML=`<section class="st-print-options" role="dialog" aria-modal="true"><div class="st-print-options-head"><div><h3>Druckumfang auswählen</h3><p>${selected.size} Unterweisung(en) ausgewählt</p></div><button class="close" data-st-action="close-print-options" data-employee-action="close-print-options">Zurück</button></div><div class="st-print-option-grid"><button class="st-print-option" data-st-print-mode="confirmation"><strong>Nur Bestätigung und Unterschriften</strong><span>Je Unterweisung genau eine A4-Seite.</span></button><button class="st-print-option" data-st-print-mode="full"><strong>Unterweisung mit Bestätigungsseite</strong><span>Inhalt, danach separate Bestätigungsseite.</span></button></div></section>`;document.body.appendChild(d)}
function header(e,x){return`<header class="st-print-header"><div class="st-print-title"><span class="st-training-number">${E(x.training.trainingNumber)}</span><h1>${E(tn(x.training,'de'))}</h1><p>${E(cn(x.training.category,'de'))}</p></div><dl><div><dt>Unterweisungs-ID</dt><dd>${E(x.training.trainingNumber)}</dd></div><div><dt>Mitarbeitende Person</dt><dd>${E(e[0])}</dd></div><div><dt>Personalnummer</dt><dd>${E(e[1])}</dd></div><div><dt>Bereich / Tätigkeit</dt><dd>${E(e[2])} · ${E(e[3])}</dd></div><div><dt>Unterweisung / Version</dt><dd>${E(tn(x.training,'de'))} · v${E(x.training.version)}</dd></div></dl></header>`}
function confirmPage(e,x){const l=e[5]||'de',c=CONF[l]||CONF.de,completed=fmt(x.record?.date||add(0));return`<section class="st-confirmation-page">${header(e,x)}<div class="st-confirmation-copy" dir="${l==='ar'?'rtl':'ltr'}"><h2>${E(c[0])}</h2><p><strong>${E(x.training.trainingNumber)} · ${E(tn(x.training,l))}</strong></p><p>${E(c[1])}</p>${l==='de'?'':`<p class="st-german-reference" dir="ltr"><strong>Deutsche Referenz:</strong> Ich bestätige, dass ich diese Unterweisung erhalten, verstanden und Gelegenheit für Rückfragen hatte.</p>`}</div><section class="st-confirmation-fields"><div class="st-form-field"><span>Durchgeführt am</span><strong>${E(completed)}</strong></div><div class="st-form-field"><span>Personalnummer der unterweisenden / beaufsichtigenden Person</span><strong>&nbsp;</strong></div><div class="st-form-field st-form-field-wide"><span>Name der unterweisenden / beaufsichtigenden Person</span><strong>&nbsp;</strong></div><div class="st-form-field"><span>Unterschrift Mitarbeitende:r</span><strong>&nbsp;</strong></div><div class="st-form-field"><span>Unterschrift unterweisende / beaufsichtigende Person</span><strong>&nbsp;</strong></div></section><footer class="st-print-footer"><span>${E(api.productVersion||'SafeTrack v0.24')}</span><span>${E(x.training.trainingNumber)} · Erstellt am ${E(fmt(add(0)))}</span></footer></section>`}
function slide(s){if(!Array.isArray(s))return'';return`<section class="st-print-slide"><h3>${E(s[0])}</h3><ul>${(Array.isArray(s[1])?s[1]:[]).map(p=>`<li>${E(p)}</li>`).join('')}</ul></section>`}
function langContent(t,l,h){return`<section class="st-print-language" dir="${l==='ar'?'rtl':'ltr'}"><span class="st-training-number">${E(t.trainingNumber)}</span><h2>${E(h)}</h2><h3>${E(tn(t,l))}</h3><p>${E(t.description?.[l]||t.description?.de||'')}</p>${(t.slides?.[l]||t.slides?.de||[]).map(slide).join('')}</section>`}
function trainingContent(e,x){const l=e[5]||'de';return`<section class="st-training-content">${header(e,x)}${langContent(x.training,l,`Unterweisung · ${LANG[l]||l.toUpperCase()}`)}${l==='de'?'':langContent(x.training,'de','Deutsche Fassung für die unterweisende Person')}</section>`}
function buildPrintSheet(mode,e,items,id=''){const s=document.createElement('section');if(id)s.id=id;s.className='st-print-sheet';s.dataset.printMode=mode;s.dataset.printOwner='employees.js';s.dataset.documentCount=String(items.length);s.innerHTML=items.map((x,i)=>`<article class="st-print-document" data-st-print-document="${i+1}" data-training-id="${E(x.training.id)}" data-training-number="${E(x.training.trainingNumber)}">${mode==='full'?trainingContent(e,x):''}${confirmPage(e,x)}</article>`).join('');return s}
function showPrintPreview(mode){const e=seed.employees.find(x=>x[1]===currentEmployeeId),items=selectedAssignments();if(!e||!items.length)return toast('Mindestens eine Unterweisung auswählen');closePrint();closePrintPreview();printContext={mode,employee:e,items:[...items]};const bg=document.createElement('div');bg.className='st-print-preview-bg';bg.setAttribute('role','dialog');bg.setAttribute('aria-modal','true');bg.innerHTML=`<div class="st-print-preview-toolbar"><div><strong>Druckvorschau</strong><span><b data-st-preview-count>${items.length}</b> Dokument(e) · ${mode==='full'?'Vollständige Unterweisung':'Bestätigung'}</span></div><div><button class="btn" data-st-action="close-print-preview" data-employee-action="close-print-preview">Zurück</button><button class="btn primary" data-st-action="execute-print" data-employee-action="execute-print">Drucken</button></div></div>`;bg.appendChild(buildPrintSheet(mode,e,items,'st-print-preview-sheet'));document.body.appendChild(bg)}
function prepareSystemPrint(){if(!printContext)return null;removeSystemPrintRoot();const root=document.createElement('section');root.id='st-system-print-root';root.dataset.documentCount=String(printContext.items.length);root.dataset.printMode=printContext.mode;root.appendChild(buildPrintSheet(printContext.mode,printContext.employee,printContext.items,'st-system-print-sheet'));document.body.appendChild(root);return root}
function executePrint(){const root=prepareSystemPrint();if(!root)return toast('Druckdokument konnte nicht erstellt werden');document.body.classList.add('st-printing');clearTimeout(printCleanupTimer);let cleaned=false;const clean=()=>{if(cleaned)return;cleaned=true;document.body.classList.remove('st-printing');removeSystemPrintRoot();window.removeEventListener('afterprint',clean);clearTimeout(printCleanupTimer)};window.addEventListener('afterprint',clean,{once:true});printCleanupTimer=setTimeout(clean,60000);requestAnimationFrame(()=>requestAnimationFrame(()=>{void root.offsetHeight;window.print()}))}
function printSelection(mode){if(!['confirmation','full'].includes(mode))return openPrintOptions();showPrintPreview(mode)}
function toggleControlled(btn){const body=document.getElementById(btn.getAttribute('aria-controls')||''),open=btn.getAttribute('aria-expanded')==='true';btn.setAttribute('aria-expanded',String(!open));if(body)body.hidden=open}
document.addEventListener('input',e=>{if(e.target.matches?.('#employee-search')&&api.state.page==='employees'){api.state.empSearch=e.target.value;refreshEmployees()}});
document.addEventListener('change',e=>{if(e.target.matches?.('#emp')&&api.state.page==='employees'){api.state.emp=e.target.value;refreshEmployees();return}const t=e.target.closest?.('[data-st-training]');if(t){t.checked?selected.add(t.dataset.stTraining):selected.delete(t.dataset.stTraining);sync();return}const c=e.target.closest?.('[data-st-category]');if(c){idsFor(c.dataset.stCategory).forEach(id=>c.checked?selected.add(id):selected.delete(id));sync()}});
document.addEventListener('click',e=>{const row=e.target.closest?.('[data-st-employee]');if(row){e.preventDefault();e.stopPropagation();api.openEmployee?.(row.dataset.stEmployee);return}const pm=e.target.closest?.('[data-st-print-mode]');if(pm){e.preventDefault();printSelection(pm.dataset.stPrintMode);return}const a=e.target.closest?.('[data-employee-action],[data-st-action]');if(!a)return;const n=a.dataset.employeeAction||a.dataset.stAction;if(n==='toggle-category'||n==='toggle-job'||n==='toggle-area')toggleControlled(a);else if(n==='clear-filters'){api.state.emp='';api.state.empSearch='';const search=document.querySelector('#employee-search'),sel=document.querySelector('#emp');if(search)search.value='';if(sel)sel.value='';refreshEmployees()}else if(n==='select-critical'||n==='select-soon'){const s=n==='select-critical'?'critical':'soon';assignments(currentEmployeeId).filter(x=>x.status===s).forEach(x=>selected.add(x.training.id));sync()}else if(n==='clear'){selected.clear();sync()}else if(n==='start')startBatch();else if(n==='print')openPrintOptions();else if(n==='close-print-options')closePrint();else if(n==='close-print-preview')closePrintPreview();else if(n==='execute-print')executePrint()},true);
document.addEventListener('click',e=>{const b=e.target.closest?.('[data-a="saveSession"]');if(!b||!batch)return;const before=records().length;setTimeout(()=>{if(records().length<=before)return;selected.delete(batch.ids[batch.index]);batch.index++;openBatch()},180)},true);
document.addEventListener('click',e=>{if(e.target.closest?.('[data-a="close"]')&&batch&&api.state.m?.t==='session')batch=null},true);
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closePrint();closePrintPreview()}});
window.__SafeTrackEmployeeGroups={owner:'employees.js',renderPage,renderProfile,groupsFor,assignments,employeeJobGroups,employeeAreaGroups,getSelected:()=>[...selected],select(ids){selected=new Set(ids);sync()},printSelection,openPrintOptions,buildPrintSheet,prepareSystemPrint,getPrintDocumentCount:()=>document.querySelectorAll('#st-system-print-root [data-st-print-document]').length,refreshEmployees};
if(api.state.page==='employees'||api.state.m?.t==='emp')api.render();
})();