import { api } from '@appdeploy/client';

const qaPrefix=new URLSearchParams(location.search).get('___keys_prefix')||'';
if(qaPrefix.startsWith('qa_')){
 let busy=false;
 const sleep=ms=>new Promise(r=>setTimeout(r,ms));
 const drawQr=async(ctx,id,x,y,size)=>{if(typeof window.qrcode!=='function')return;const qr=window.qrcode(0,'M');qr.addData(id);qr.make();const img=new Image();img.src=qr.createDataURL(7,4);await img.decode();ctx.drawImage(img,x,y,size,size)};
 async function createDoc(mode,pageCount=3){const employee=window.SafeTrackSeed?.employees?.[0],catalog=window.__SafeTrack?.catalog||window.SafeTrackSeed?.trainings||[],training=catalog.find(t=>Array.isArray(t.roles)&&t.roles.includes('all'))||catalog[0];if(!employee||!training)throw new Error('QA Stammdaten fehlen.');const date=new Date().toISOString().slice(0,10),clientToken=`${qaPrefix}-v022-${mode}`,fingerprint=`QA22|${qaPrefix}|${mode}|${employee[1]}|${training.id}`,prepared=await api.post('/api/documents/prepare',{documents:[{clientToken,fingerprint,trainingKey:training.id,trainingId:training.trainingNumber||'ST-UW-001',trainingName:training.title?.de||training.id,version:training.version||'1.0',date,participants:[{name:employee[0],pnr:employee[1],role:employee[3]}],instructor:'QA Führungskraft',instructorPersonnel:employee[1],pageCount}]}),documentId=prepared.data.documents?.[0]?.documentId;if(!documentId)throw new Error('QA Dokument konnte nicht angelegt werden.');await api.post(`/api/documents/${documentId}/snapshot`,{html:`<article><h1>Schulungsbestätigung</h1><p>${documentId}</p><p>Seite 1/${pageCount}</p></article>`});await api.post(`/api/documents/${documentId}/printed`,{});const r=await api.get(`/api/documents/${documentId}`);return r.data.document}
 async function drawPage(doc,pageNumber,total,idOverride=''){const id=idOverride||doc.documentId,c=document.createElement('canvas');c.width=1400;c.height=1800;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.fillStyle='#111';x.font='700 50px Arial';x.fillText('Schulungsbestätigung',80,105);x.font='700 31px Arial';x.fillText(`Dokument-ID: ${id}`,80,180);x.fillText(`Unterweisungs-ID: ${doc.trainingId}`,80,235);x.fillText(`Version: ${doc.version}`,80,285);x.fillText(`Seite ${pageNumber}/${total}`,80,340);await drawQr(x,id,1050,70,250);let y=480;x.font='700 25px Arial';x.fillText('Mitarbeitende Person',80,y);x.fillText('PNr.',510,y);x.fillText('Tätigkeit',750,y);x.fillText('Unterschrift',1090,y);y+=50;x.font='24px Arial';for(const p of doc.participants||[]){x.fillText(p.name||'',80,y);x.font='700 24px Arial';x.fillText(p.pnr||'',510,y);x.font='24px Arial';x.fillText(String(p.role||'').slice(0,24),750,y);x.lineWidth=3;x.beginPath();x.moveTo(1090,y-5);x.bezierCurveTo(1140,y-35,1180,y+30,1230,y-10);x.bezierCurveTo(1260,y-28,1290,y+24,1320,y-4);x.stroke();y+=75}x.font='700 24px Arial';x.fillText(`Seite ${pageNumber}/${total}`,1080,1710);const data=c.toDataURL('image/png').split(',')[1];let qrId='';try{if(typeof window.jsQR==='function'){const d=x.getImageData(0,0,c.width,c.height),hit=window.jsQR(d.data,d.width,d.height,{inversionAttempts:'attemptBoth'});qrId=hit?.data||''}}catch{}return{data,qrId,mimeType:'image/png'}}
 async function submit(mode){const doc=await createDoc(mode,3),spec=mode==='missing'?[[1,''],[3,'']]:mode==='duplicate'?[[1,''],[2,''],[2,''],[3,'']]:mode==='foreign'?[[1,''],[2,'ST-DOC-2099-999999'],[3,'']]:[[1,''],[2,''],[3,'']],pages=[];for(const [n,id] of spec)pages.push(await drawPage(doc,n,3,id));const first=pages[0],stored=await api.post('/api/uploads/store',{filename:`QA-${mode}-${doc.documentId}.png`,mimeType:'image/png',size:Math.ceil(first.data.length*.75),content:first.data}),uploadId=stored.data.uploadId;for(let i=0;i<pages.length;i+=5){const batch=pages.slice(i,i+5);await api.post(`/api/uploads/${uploadId}/analyze`,{images:batch.map(p=>({data:p.data,mimeType:p.mimeType})),qrIds:batch.map(p=>p.qrId||''),pageOffset:i})}return(await api.post(`/api/uploads/${uploadId}/finalize`,{})).data}
 function makePdf(count){const bodies=new Map(),max=2+count*2,kids=[];for(let i=0;i<count;i++)kids.push(`${3+i*2} 0 R`);bodies.set(1,'<< /Type /Catalog /Pages 2 0 R >>');bodies.set(2,`<< /Type /Pages /Kids [${kids.join(' ')}] /Count ${count} >>`);for(let i=0;i<count;i++){const p=3+i*2,s=p+1;bodies.set(p,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << >> /Contents ${s} 0 R >>`);bodies.set(s,'<< /Length 0 >>\nstream\n\nendstream')}let out='%PDF-1.4\n',offsets=Array(max+1).fill(0);for(let n=1;n<=max;n++){offsets[n]=out.length;out+=`${n} 0 obj\n${bodies.get(n)}\nendobj\n`}const xref=out.length;out+=`xref\n0 ${max+1}\n0000000000 65535 f \n`;for(let n=1;n<=max;n++)out+=`${String(offsets[n]).padStart(10,'0')} 00000 n \n`;out+=`trailer\n<< /Size ${max+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new File([out],'QA-30-Seiten.pdf',{type:'application/pdf'})}
 function refresh(){document.querySelector('.st-v021-registry-bg')?.remove();document.querySelector('[data-v019-documents]')?.click()}
 async function run(btn,mode){if(busy)return;busy=true;document.querySelectorAll('[data-v022-qa]').forEach(x=>x.disabled=true);const original=btn.textContent;btn.textContent='QA läuft …';try{if(mode==='pdf30'){const pages=await window.__SafeTrackV022Upload?.pdfPages(makePdf(30));if(pages?.length!==30)throw new Error(`Nur ${pages?.length||0}/30 Seiten erkannt.`);btn.textContent='QA PDF: 30/30 Seiten akzeptiert';await sleep(1200);return}const result=await submit(mode),pc=result.document?.autoCheck?.pageCheck;if(mode==='complete'&&pc?.ok!==true)throw new Error('Vollständige Seitenprüfung fehlgeschlagen.');if(mode!=='complete'&&pc?.ok!==false)throw new Error('Kritische Seitenabweichung wurde nicht erkannt.');btn.textContent=mode==='complete'?'QA: 3/3 vollständig':`QA: ${mode} blockiert`;await sleep(600);refresh()}catch(e){console.error(e);btn.textContent=e?.message||'QA fehlgeschlagen'}finally{busy=false;setTimeout(()=>document.querySelectorAll('[data-v022-qa]').forEach(x=>x.disabled=false),300);if(btn.textContent==='QA läuft …')btn.textContent=original}}
 function enhance(){const actions=document.querySelector('.st-v021-registry-actions');if(!actions||actions.querySelector('[data-v022-qa]'))return;const defs=[['complete','QA 3 Seiten vollständig'],['missing','QA Seite fehlt'],['duplicate','QA Seite doppelt'],['foreign','QA fremde Seite'],['pdf30','QA 30-Seiten-PDF']];for(const [mode,label] of defs){const b=document.createElement('button');b.type='button';b.className='btn';b.dataset.v022Qa=mode;b.textContent=label;actions.prepend(b)}}
 new MutationObserver(enhance).observe(document.documentElement,{childList:true,subtree:true});enhance();
 document.addEventListener('click',e=>{const b=e.target.closest?.('[data-v022-qa]');if(b){e.preventDefault();void run(b,b.dataset.v022Qa)}},true);
}
