import { api } from '@appdeploy/client';

const VERSION='SafeTrack v0.22';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let pending=false;
function syncVersion(){if(window.__SafeTrack)window.__SafeTrack.version=VERSION;document.querySelectorAll('.st-version-badge').forEach(x=>{x.textContent=VERSION;x.setAttribute('aria-label',`Aktuelle Version ${VERSION}`)});document.title=document.title.replace(/SafeTrack v0\.\d+/,VERSION);const note=document.querySelector('.st-v021-upload-note');if(note)note.textContent='Mehrere PDF/JPG/PNG gleichzeitig möglich · max. 20 MB je Datei · PDF max. 30 Seiten'}
function listText(values,total){return Array.isArray(values)&&values.length?values.map(v=>`${v}/${total}`).join(', '):'—'}
function pageMarkup(pc){const ok=pc?.ok===true,total=Number(pc?.expectedCount||0),received=Number(pc?.receivedCount||0),errors=Array.isArray(pc?.errors)?pc.errors:[];return`<section class="st-v022-pages ${ok?'ok':'critical'}" data-v022-pages><header><div><h3>Seitenprüfung</h3><p>Strenge Prüfung von QR, Dokument-ID und Seite x/y.</p></div><strong>${ok?'Vollständig':'Kritische Abweichung'}</strong></header><div class="st-v022-page-grid"><div><span>Erwartet</span><strong>${total}</strong></div><div><span>Erkannt</span><strong>${received}</strong></div><div><span>Fehlend</span><strong>${listText(pc?.missingPages,total)}</strong></div><div><span>Doppelt</span><strong>${listText(pc?.duplicatePages,total)}</strong></div><div><span>Fremd / falsch</span><strong>${Array.isArray(pc?.foreignPages)&&pc.foreignPages.length?pc.foreignPages.join(', '):'—'}</strong></div><div><span>Nicht lesbar</span><strong>${Array.isArray(pc?.unreadablePages)&&pc.unreadablePages.length?pc.unreadablePages.join(', '):'—'}</strong></div></div>${errors.length?`<ul>${errors.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p class="st-v022-page-ok">Alle erwarteten Seiten wurden eindeutig und widerspruchsfrei erkannt.</p>'}</section>`}
async function enhanceDetail(){const detail=document.querySelector('.st-v020-detail');if(!detail||detail.dataset.v022Loading==='1'||detail.querySelector('[data-v022-pages]'))return;const id=detail.querySelector('h2')?.textContent.trim();if(!/^ST-DOC-\d{4}-\d{6}$/.test(id||''))return;detail.dataset.v022Loading='1';try{const r=await api.get(`/api/documents/${encodeURIComponent(id)}`),d=r.data.document,pc=d?.autoCheck?.pageCheck;if(!pc)return;const check=detail.querySelector('.st-v021-check'),holder=document.createElement('div');holder.innerHTML=pageMarkup(pc);const section=holder.firstElementChild;if(check&&section)check.insertAdjacentElement('afterend',section);else if(section)detail.querySelector('.st-v020-participants')?.insertAdjacentElement('beforebegin',section);if(pc.ok!==true){detail.querySelector('.st-v020-status')?.classList.add('st-v022-critical-status');const btn=detail.querySelector('[data-v021-complete]');if(btn){btn.disabled=true;btn.title='Abschluss gesperrt: Seitenprüfung nicht bestanden.'}}}catch(e){console.warn('SafeTrack v0.22 page check UI failed',e)}finally{detail.dataset.v022Loading='0'}}
function schedule(){if(pending)return;pending=true;setTimeout(()=>{pending=false;syncVersion();void enhanceDetail()},0)}
new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});
document.addEventListener('click',e=>{if(e.target.closest?.('[data-v021-open-doc],[data-v019-documents],[data-v021-close-detail]'))setTimeout(schedule,0)},true);
syncVersion();schedule();
