import { api } from '@appdeploy/client';

const qaPrefix=new URLSearchParams(location.search).get('___keys_prefix')||'';
if(qaPrefix.startsWith('qa_')){
 let busy=false;
 const sleep=ms=>new Promise(r=>setTimeout(r,ms));
 const drawQr=async(ctx,id,x,y,size)=>{if(typeof window.qrcode!=='function')return;const qr=window.qrcode(0,'M');qr.addData(id);qr.make();const img=new Image();img.src=qr.createDataURL(7,4);await img.decode();ctx.drawImage(img,x,y,size,size)};
 const makeReturn=async doc=>{const c=document.createElement('canvas');c.width=1400;c.height=1800;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.fillStyle='#111';x.font='700 52px Arial';x.fillText('Schulungsbestätigung',90,110);x.font='700 34px Arial';x.fillText(`Dokument-ID: ${doc.documentId}`,90,190);x.fillText(`Unterweisungs-ID: ${doc.trainingId}`,90,245);x.fillText(`Version: ${doc.version}`,90,300);x.font='26px Arial';x.fillText(`Durchgeführt am: ${doc.date}`,90,350);await drawQr(x,doc.documentId,1030,80,260);let y=470;x.font='700 26px Arial';x.fillText('Mitarbeitende Person',90,y);x.fillText('PNr.',520,y);x.fillText('Tätigkeit',760,y);x.fillText('Unterschrift',1110,y);y+=35;x.font='24px Arial';for(const p of doc.participants||[]){x.strokeStyle='#777';x.beginPath();x.moveTo(80,y+38);x.lineTo(1320,y+38);x.stroke();x.fillStyle='#111';x.fillText(p.name||'',90,y+25);x.font='700 24px Arial';x.fillText(p.pnr||'',520,y+25);x.font='24px Arial';x.fillText(String(p.role||'').slice(0,25),760,y+25);x.strokeStyle='#111';x.lineWidth=3;x.beginPath();x.moveTo(1110,y+18);x.bezierCurveTo(1150,y-8,1190,y+42,1240,y+8);x.bezierCurveTo(1270,y-15,1290,y+32,1310,y+12);x.stroke();y+=62}x.font='700 28px Arial';x.fillText('Unterschriften vorhanden',90,Math.min(y+100,1680));const data=c.toDataURL('image/png').split(',')[1];let qrId='';try{if(typeof window.jsQR==='function'){const d=x.getImageData(0,0,c.width,c.height),hit=window.jsQR(d.data,d.width,d.height,{inversionAttempts:'attemptBoth'});qrId=hit?.data||''}}catch{}return{data,qrId,size:Math.ceil(data.length*0.75)}};
 const refreshRegistry=()=>{document.querySelector('.st-v021-registry-bg')?.remove();document.querySelector('[data-v019-documents]')?.click()};
 async function simulate(btn){if(busy)return;busy=true;btn.disabled=true;btn.textContent='QA Rücklauf wird geprüft …';try{const r=await api.get('/api/documents'),doc=(r.data.documents||[]).find(d=>d.status==='printed'||d.status==='ready');if(!doc)throw new Error('Zuerst ein Dokument drucken und bestätigen.');const f=await makeReturn(doc),stored=await api.post('/api/uploads/store',{filename:`QA-${doc.documentId}.png`,mimeType:'image/png',size:f.size,content:f.data}),id=stored.data.uploadId;await api.post(`/api/uploads/${id}/analyze`,{images:[{data:f.data,mimeType:'image/png'}],qrIds:f.qrId?[f.qrId]:[],pageOffset:0});const fin=await api.post(`/api/uploads/${id}/finalize`,{});if(!fin.data.matched)throw new Error('QA Rücklauf konnte nicht zugeordnet werden.');btn.textContent=`QA geprüft: ${fin.data.document.documentId}`;await sleep(500);refreshRegistry()}catch(e){console.error(e);btn.textContent=e?.message||'QA Rücklauf fehlgeschlagen';btn.disabled=false}finally{busy=false}}
 function enhance(){const actions=document.querySelector('.st-v021-registry-actions');if(!actions||actions.querySelector('[data-v021-qa-return]'))return;const b=document.createElement('button');b.type='button';b.className='btn';b.dataset.v021QaReturn='1';b.textContent='QA Rücklauf simulieren';actions.prepend(b)}
 new MutationObserver(enhance).observe(document.documentElement,{childList:true,subtree:true});enhance();
 document.addEventListener('click',e=>{const b=e.target.closest?.('[data-v021-qa-return]');if(b){e.preventDefault();void simulate(b)}},true);
}
