(()=>{'use strict';
const VERSION='SafeTrack v0.20';
const REGISTRY_KEY='safetrack-v019-documents';
const STATE_KEY='safetrack-static-v6';
const DB_NAME='safetrack-v020-documents';
const STORE='artifacts';
const STATUS={ready:'Druckbereit',printed:'Gedruckt – Rückupload ausstehend',uploaded:'Rückupload erhalten – Prüfung ausstehend',done:'Abgeschlossen – Mitarbeitenden zugeordnet'};
const nativePrint=window.print.bind(window);
let enhancing=false,scheduled=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function readRegistry(){try{const x=JSON.parse(localStorage.getItem(REGISTRY_KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function writeRegistry(items){localStorage.setItem(REGISTRY_KEY,JSON.stringify(items.slice(0,250)))}
function normalizeStatus(s){if(s===STATUS.printed||s===STATUS.uploaded||s===STATUS.done||s===STATUS.ready)return s;return STATUS.ready}
function headerValue(doc,label){const rows=[...doc.querySelectorAll('.st-group-print-header dl>div')];const row=rows.find(x=>x.querySelector('dt')?.textContent.trim()===label);return row?.querySelector('dd')?.textContent.trim()||''}
function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:'id'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function getArtifact(id){try{const db=await openDb();return await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),req=tx.objectStore(STORE).get(id);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error)})}catch{return null}}
async function putArtifact(data){try{const db=await openDb();const old=await getArtifact(data.id)||{};await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put({...old,...data});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}catch(e){console.warn('SafeTrack v0.20 IndexedDB write failed',e)}}
function updateRegistry(ids,patch){const set=new Set(Array.isArray(ids)?ids:[ids]);const items=readRegistry();items.forEach(r=>{if(set.has(r.id))Object.assign(r,typeof patch==='function'?patch(r):patch)});writeRegistry(items);return items.filter(r=>set.has(r.id))}
function syncVersion(){if(window.__SafeTrack)window.__SafeTrack.version=VERSION;document.querySelectorAll('.st-version-badge').forEach(x=>{if(x.textContent!==VERSION)x.textContent=VERSION;x.setAttribute('aria-label',`Aktuelle Version ${VERSION}`)});document.querySelectorAll('.st-print-footer span:first-child').forEach(x=>{if(x.textContent!==VERSION)x.textContent=VERSION});if(document.title.includes('SafeTrack'))document.title=document.title.replace(/SafeTrack v0\.\d+/,VERSION)}
function removeDateColumn(doc){if(doc.dataset.v020Layout==='1')return;const table=doc.querySelector('.st-group-confirmation-table');if(!table)return;table.querySelector('col.st-col-date')?.remove();[...table.querySelectorAll('thead th')].forEach(th=>{if(th.textContent.trim()==='Datum')th.remove()});table.querySelectorAll('td.st-group-person-date').forEach(td=>td.remove());doc.classList.add('st-v020-four-cols');doc.dataset.v020Layout='1'}
function enhanceDocuments(root=document){root.querySelectorAll?.('.st-group-confirmation-document').forEach(removeDateColumn)}
function schedule(){if(scheduled)return;scheduled=true;setTimeout(()=>{scheduled=false;if(enhancing)return;enhancing=true;try{syncVersion();enhanceDocuments(document)}finally{enhancing=false}},0)}
function collectParticipants(pages){const out=[],seen=new Set();pages.forEach(page=>page.querySelectorAll('.st-group-confirmation-table tbody tr').forEach(tr=>{const pnr=tr.querySelector('.st-group-person-number')?.textContent.trim()||'';if(!pnr||seen.has(pnr))return;seen.add(pnr);out.push({name:tr.querySelector('.st-group-person-name')?.textContent.trim()||'',pnr,role:tr.querySelector('.st-group-person-role')?.textContent.trim()||''})}));return out}
function collectPrintableDocuments(){enhanceDocuments(document);const root=document.querySelector('#st-group-system-print-root');if(!root)return[];const grouped=new Map();root.querySelectorAll('.st-group-confirmation-document').forEach(page=>{const id=page.dataset.documentId||page.querySelector('.st-doc-id-copy strong')?.textContent.trim()||'';if(!id)return;if(!grouped.has(id))grouped.set(id,[]);grouped.get(id).push(page)});const registry=readRegistry();const now=new Date().toISOString();const docs=[];grouped.forEach((pages,id)=>{const first=pages[0],participants=collectParticipants(pages);const fields=[...pages].reverse().map(p=>p.querySelector('.st-group-instructor-fields')).find(Boolean);const fieldDivs=fields?[...fields.children]:[];const entry={id,trainingKey:first.dataset.trainingId||'',trainingId:first.dataset.trainingNumber||headerValue(first,'Unterweisungs-ID'),trainingName:first.querySelector('.st-group-print-header h2')?.textContent.trim()||'',version:headerValue(first,'Version'),date:headerValue(first,'Durchgeführt am'),participants,pnrs:participants.map(p=>p.pnr),participantCount:participants.length,participantsCount:participants.length,instructor:fieldDivs[0]?.querySelector('strong')?.textContent.trim()||'',instructorPersonnel:fieldDivs[1]?.querySelector('strong')?.textContent.trim()||'',pageCount:pages.length,status:STATUS.ready,preparedAt:now,updatedAt:now};let existing=registry.find(r=>r.id===id);if(existing)Object.assign(existing,entry,{createdAt:existing.createdAt||now,status:existing.status===STATUS.done?STATUS.done:STATUS.ready});else{existing={...entry,createdAt:now};registry.unshift(existing)}putArtifact({id,pagesHtml:pages.map(p=>p.outerHTML),savedAt:now});docs.push(existing)});writeRegistry(registry);return docs}
function statusClass(status){return status===STATUS.done?'done':status===STATUS.uploaded?'uploaded':status===STATUS.printed?'printed':'ready'}
function showSavedDialog(ids){document.querySelector('.st-v020-saved-bg')?.remove();const list=ids.map(id=>`<li><strong>${esc(id)}</strong></li>`).join('');const bg=document.createElement('div');bg.className='st-v020-saved-bg';bg.innerHTML=`<section class="st-v020-saved" role="dialog" aria-modal="true" aria-label="Dokument gespeichert"><span class="st-v020-success-mark">✓</span><h2>Dokument erfolgreich gespeichert und druckbereit.</h2><p>Die Dokument-ID und alle Druckdaten wurden im Dokumentenregister gespeichert.</p><ul>${list}</ul><button class="btn primary" data-v020-print-confirm data-ids="${esc(ids.join(','))}">Druck bestätigt – Dokumente öffnen</button></section>`;document.body.appendChild(bg)}
function openRegistry(){document.querySelector('.st-doc-registry-bg')?.remove();document.querySelector('.st-v020-registry-bg')?.remove();const items=readRegistry().map(r=>({...r,status:normalizeStatus(r.status)}));writeRegistry(items);const rows=items.length?items.map(r=>`<button class="st-v020-doc-row" data-v020-open-doc="${esc(r.id)}"><div><strong>${esc(r.id)}</strong><span>${esc(r.trainingId||'')} · ${esc(r.trainingName||'')}</span></div><div><span>Durchgeführt am</span><strong>${esc(r.date||'—')}</strong></div><div><span>Teilnehmende</span><strong>${Number(r.participantCount??(Array.isArray(r.participants)?r.participants.length:r.participants)??r.pnrs?.length??0)}</strong></div><div><span>Status</span><strong class="st-v020-status ${statusClass(r.status)}">${esc(r.status)}</strong></div></button>`).join(''):'<div class="empty">Noch keine Dokumente gespeichert.</div>';const bg=document.createElement('div');bg.className='st-v020-registry-bg';bg.innerHTML=`<section class="st-v020-registry" role="dialog" aria-modal="true" aria-label="Dokumente"><header><div><h2>Dokumente</h2><p>Gespeicherte Schulungsbestätigungen und Rücklaufstatus.</p></div><button class="btn" data-v020-close-registry>Zurück</button></header><div class="st-v020-doc-list">${rows}</div></section>`;document.body.appendChild(bg)}
async function openDetail(id){document.querySelector('.st-v020-detail-bg')?.remove();const entry=readRegistry().find(r=>r.id===id);if(!entry)return;const artifact=await getArtifact(id);const upload=entry.uploadName?`<div class="st-v020-uploaded"><strong>${esc(entry.uploadName)}</strong><span>${entry.uploadSize?Math.round(entry.uploadSize/1024)+' KB':''}${entry.uploadedAt?' · '+new Date(entry.uploadedAt).toLocaleString('de-DE'):''}</span>${artifact?.signedFile?'<button class="btn" data-v020-open-upload="'+esc(id)+'">Datei öffnen</button>':''}</div>`:'<p class="st-v020-muted">Noch kein unterschriebenes Dokument hochgeladen.</p>';const participantRows=(Array.isArray(entry.participants)?entry.participants:[]).map(p=>`<tr><td>${esc(p.name)}</td><td><strong>${esc(p.pnr)}</strong></td><td>${esc(p.role)}</td></tr>`).join('');const canClose=normalizeStatus(entry.status)===STATUS.uploaded;const bg=document.createElement('div');bg.className='st-v020-detail-bg';bg.innerHTML=`<section class="st-v020-detail" role="dialog" aria-modal="true" aria-label="Dokument ${esc(id)}"><header><div><h2>${esc(id)}</h2><p>${esc(entry.trainingId||'')} · ${esc(entry.trainingName||'')}</p></div><button class="btn" data-v020-close-detail>Zurück</button></header><div class="st-v020-detail-grid"><div><span>Status</span><strong class="st-v020-status ${statusClass(normalizeStatus(entry.status))}">${esc(normalizeStatus(entry.status))}</strong></div><div><span>Durchgeführt am</span><strong>${esc(entry.date||'—')}</strong></div><div><span>Version</span><strong>${esc(entry.version||'—')}</strong></div><div><span>Teilnehmende</span><strong>${Number(entry.participantCount??(Array.isArray(entry.participants)?entry.participants.length:entry.participants)??entry.pnrs?.length??0)}</strong></div><div><span>Unterweisende Person</span><strong>${esc(entry.instructor||'—')}</strong></div><div><span>PNr.</span><strong>${esc(entry.instructorPersonnel||'—')}</strong></div></div><div class="st-v020-actions"><button class="btn" data-v020-preview-doc="${esc(id)}">Gespeichertes Dokument öffnen</button><button class="btn" data-v020-reprint="${esc(id)}">Erneut drucken</button></div><section class="st-v020-upload"><h3>Unterschriebenes Dokument</h3>${upload}<label class="btn primary st-v020-file-label">Unterschriebenes Dokument hochladen<input type="file" data-v020-upload="${esc(id)}" accept="application/pdf,image/jpeg,image/png" hidden></label></section><section class="st-v020-participants"><h3>Zugeordnete Mitarbeitende</h3><table><thead><tr><th>Name</th><th>PNr.</th><th>Tätigkeit</th></tr></thead><tbody>${participantRows}</tbody></table></section><footer><button class="btn primary st-v020-complete" data-v020-complete="${esc(id)}" ${canClose?'':'disabled'}>Prüfen & abschließen</button><small>Erst nach der Prüfung werden die Unterweisungen den Mitarbeitenden als abgeschlossen zugeordnet.</small></footer></section>`;document.body.appendChild(bg)}
async function previewSaved(id){const artifact=await getArtifact(id);if(!artifact?.pagesHtml?.length)return alert('Für dieses ältere Dokument ist noch keine gespeicherte Druckansicht vorhanden.');document.querySelector('.st-v020-snapshot-bg')?.remove();const bg=document.createElement('div');bg.className='st-v020-snapshot-bg';bg.innerHTML=`<div class="st-v020-snapshot-toolbar"><strong>${esc(id)}</strong><button class="btn" data-v020-close-snapshot>Zurück</button></div><section class="st-v020-snapshot-pages">${artifact.pagesHtml.join('')}</section>`;document.body.appendChild(bg);enhanceDocuments(bg)}
async function reprintSaved(id){const artifact=await getArtifact(id);if(!artifact?.pagesHtml?.length)return alert('Keine gespeicherte Druckansicht vorhanden.');document.querySelector('#st-v020-reprint-root')?.remove();const root=document.createElement('section');root.id='st-v020-reprint-root';root.innerHTML=artifact.pagesHtml.join('');document.body.appendChild(root);enhanceDocuments(root);document.body.classList.add('st-v020-reprinting');const clean=()=>{document.body.classList.remove('st-v020-reprinting');root.remove();window.removeEventListener('afterprint',clean)};window.addEventListener('afterprint',clean,{once:true});nativePrint();setTimeout(clean,30000)}
async function saveUpload(id,file){if(!file)return;const valid=['application/pdf','image/jpeg','image/png'].includes(file.type);if(!valid)return alert('Bitte PDF, JPG oder PNG auswählen.');const uploadedAt=new Date().toISOString();await putArtifact({id,signedFile:file,signedFileName:file.name,signedFileType:file.type,signedFileSize:file.size,uploadedAt});updateRegistry(id,{status:STATUS.uploaded,uploadName:file.name,uploadType:file.type,uploadSize:file.size,uploadedAt,updatedAt:uploadedAt});await openDetail(id)}
async function openUpload(id){const artifact=await getArtifact(id);if(!artifact?.signedFile)return;const url=URL.createObjectURL(artifact.signedFile),a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}
function completeAssignments(entry){if(!entry.trainingKey||!Array.isArray(entry.participants)||!entry.participants.length)return false;let state;try{state=JSON.parse(localStorage.getItem(STATE_KEY)||'null')}catch{state=null}if(!state||typeof state!=='object')state={catalog:window.__SafeTrack?.catalog||window.SafeTrackSeed?.trainings||[],records:[]};if(!Array.isArray(state.records))state.records=[];const pset=new Set(entry.participants.map(p=>p.pnr));state.records=state.records.filter(r=>!(pset.has(r.employeeId)&&r.trainingId===entry.trainingKey));entry.participants.forEach(p=>state.records.push({id:`DOC-${entry.id}-${p.pnr}-${entry.trainingKey}`,employeeId:p.pnr,employeeName:p.name,trainingId:entry.trainingKey,trainingNumber:entry.trainingId,date:entry.date,instructor:entry.instructor||'',instructorPersonnel:entry.instructorPersonnel||'',documentId:entry.id,source:'signed-document',completedAt:new Date().toISOString()}));localStorage.setItem(STATE_KEY,JSON.stringify(state));return true}
async function completeDocument(id){const items=readRegistry(),entry=items.find(r=>r.id===id);if(!entry||normalizeStatus(entry.status)!==STATUS.uploaded)return;if(!confirm(`${entry.id} abschließen und ${entry.participants?.length||0} Mitarbeitenden zuordnen?`))return;if(!completeAssignments(entry))return alert('Zuordnungsdaten unvollständig.');entry.status=STATUS.done;entry.completedAt=new Date().toISOString();entry.updatedAt=entry.completedAt;writeRegistry(items);await openDetail(id)}
function installPrintLifecycle(){if(window.__SafeTrackV020PrintWrapped)return;window.__SafeTrackV020PrintWrapped=true;window.print=function(){if(document.body.classList.contains('st-v020-reprinting'))return nativePrint();const isGroup=document.body.classList.contains('st-group-printing')||document.querySelector('#st-group-system-print-root');if(!isGroup)return nativePrint();const docs=collectPrintableDocuments();const ids=docs.map(d=>d.id);nativePrint();setTimeout(()=>{if(ids.length)showSavedDialog(ids)},0)}}
function interceptDocumentsNav(e){if(!e.target.closest?.('[data-v019-documents]'))return;setTimeout(()=>{document.querySelector('.st-doc-registry-bg')?.remove();openRegistry()},0)}
document.addEventListener('click',e=>{interceptDocumentsNav(e);const ack=e.target.closest?.('[data-v020-print-confirm]');if(ack){const ids=(ack.dataset.ids||'').split(',').filter(Boolean),now=new Date().toISOString();updateRegistry(ids,{status:STATUS.printed,printedAt:now,updatedAt:now});document.querySelector('.st-v020-saved-bg')?.remove();openRegistry();return}const row=e.target.closest?.('[data-v020-open-doc]');if(row){openDetail(row.dataset.v020OpenDoc);return}if(e.target.closest?.('[data-v020-close-registry]')){document.querySelector('.st-v020-registry-bg')?.remove();return}if(e.target.closest?.('[data-v020-close-detail]')){document.querySelector('.st-v020-detail-bg')?.remove();return}const preview=e.target.closest?.('[data-v020-preview-doc]');if(preview){previewSaved(preview.dataset.v020PreviewDoc);return}const reprint=e.target.closest?.('[data-v020-reprint]');if(reprint){reprintSaved(reprint.dataset.v020Reprint);return}if(e.target.closest?.('[data-v020-close-snapshot]')){document.querySelector('.st-v020-snapshot-bg')?.remove();return}const open=e.target.closest?.('[data-v020-open-upload]');if(open){openUpload(open.dataset.v020OpenUpload);return}const complete=e.target.closest?.('[data-v020-complete]');if(complete){completeDocument(complete.dataset.v020Complete)}},true);
document.addEventListener('change',e=>{const input=e.target.closest?.('[data-v020-upload]');if(input)saveUpload(input.dataset.v020Upload,input.files?.[0])},true);
new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});
installPrintLifecycle();schedule();
window.__SafeTrackV020={version:VERSION,status:STATUS,openDocuments:openRegistry};
})();