(()=>{'use strict';
const seed=window.SafeTrackSeed,api=window.__SafeTrack;
if(!seed||!api)return;
const L=seed.langs,N={de:'Deutsch',pl:'Polski',ru:'Русский',ar:'العربية',tr:'Türkçe',hu:'Magyar',ro:'Română'};
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cn=c=>seed.categories?.[c]?.de||c,rn=r=>seed.roles?.[r]?.de||r;
const groupSelected=()=>new Set(window.__SafeTrackGroupTraining?.getSelectedTrainings?.()||[]);
function card(t,selectedIds){return`<article class="card training ${t.active===false?'inactive':''}" data-training-card="${E(t.id)}"><div class="training-top"><label class="st-group-training-check"><input type="checkbox" data-group-training="${E(t.id)}" ${selectedIds.has(t.id)?'checked':''}><span>Für Gruppenunterweisung auswählen</span></label><div><span class="st-training-number">${E(t.trainingNumber)}</span><h4>${E(t.title?.de||t.id)}</h4><p>${E(t.description?.de||'')}</p></div><div class="code">${E(t.icon)}</div></div><div class="meta"><span class="badge">${E(t.trainingNumber)}</span><span class="badge">v${E(t.version)}</span><span class="badge">${Number(t.months)||0} Monate</span>${t.questions&&Object.keys(t.questions).length?'<span class="badge">Wissensfragen</span>':''}</div><div class="roles">${(t.roles||[]).slice(0,5).map(r=>`<span>${E(rn(r))}</span>`).join('')}</div><div class="actions"><button class="btn small" data-training-action="edit" data-id="${E(t.id)}">Bearbeiten</button><button class="btn small" data-training-action="copy" data-id="${E(t.id)}">Duplizieren</button><button class="btn primary small" data-training-action="start" data-id="${E(t.id)}" ${t.active===false?'disabled':''}>Starten</button></div></article>`}
function filtered(){const f=api.state.f||{},all=api.catalog;return all.filter(t=>(!f.s||(`${t.trainingNumber} ${t.id} ${t.title?.de||''}`).toLowerCase().includes(String(f.s).toLowerCase()))&&(!f.c||t.category===f.c)&&(!f.r||(t.roles||[]).includes('all')||(t.roles||[]).includes(f.r))&&(!f.a||(f.a==='active'?t.active!==false:t.active===false)))}
function renderCatalog(){const f=api.state.f||{},a=filtered(),selectedIds=groupSelected(),groups=Object.keys(seed.categories).map(c=>[c,a.filter(t=>t.category===c)]).filter(x=>x[1].length),count=selectedIds.size;return`<section class="card" data-trainings-owner="trainings.js"><div class="section-head"><div><h3>Unterweisungskatalog</h3><p class="muted">${a.length}/${api.catalog.length} Unterweisungen</p></div><div class="actions"><button class="btn" data-training-action="export">JSON exportieren</button><button class="btn" data-training-action="import">JSON importieren</button><button class="btn" data-training-action="reset">Testdaten zurücksetzen</button><button class="btn primary" data-training-action="edit">Hinzufügen</button><input id="file" type="file" accept="application/json" hidden></div></div><div class="panel"><div class="filters"><input id="fs" value="${E(f.s||'')}" placeholder="ID oder Titel suchen"><select id="fc"><option value="">Alle Kategorien</option>${Object.keys(seed.categories).map(c=>`<option value="${E(c)}" ${f.c===c?'selected':''}>${E(cn(c))}</option>`).join('')}</select><select id="fr"><option value="">Alle Tätigkeiten</option>${Object.keys(seed.roles).filter(r=>r!=='all').map(r=>`<option value="${E(r)}" ${f.r===r?'selected':''}>${E(rn(r))}</option>`).join('')}</select><select id="fa"><option value="active">Aktiv</option><option value="archived" ${f.a==='archived'?'selected':''}>Archiviert</option><option value="" ${f.a===''?'selected':''}>Alle</option></select></div></div></section>${groups.map(([c,items],i)=>{const id=`st-training-category-${i}`;return`<section class="group" data-training-category="${E(c)}"><div class="group-title" role="button" tabindex="0" data-training-action="toggle-category" aria-expanded="false" aria-controls="${id}"><h3>${E(cn(c))}</h3><span class="count">${items.length}</span><span class="st-chevron" aria-hidden="true"></span></div><div class="training-grid" id="${id}" hidden style="display:none">${items.map(t=>card(t,selectedIds)).join('')}</div></section>`}).join('')}<div class="st-group-training-bar"><div><strong><span data-group-training-count>${count}</span> Unterweisung(en) ausgewählt</strong><small>Mehrere Unterweisungen können gemeinsam geplant werden.</small></div><div class="st-group-training-bar-actions"><button class="btn" data-group-action="clear-trainings">Auswahl aufheben</button><button class="btn primary" data-group-action="assign-employees" ${count?'':'disabled'}>Mitarbeitende zuweisen</button></div></div>`}
function renderEditModal(m){const id=m?.id||'',t=id?api.catalog.find(x=>x.id===id):{id:'',trainingNumber:api.nextTrainingNumber(),icon:'NE',category:'general',roles:[],version:'1.0',months:12,active:true,title:{},description:{},slides:{},questions:{},custom:true};if(!t)return'';return`<div class="modal-bg"><div class="modal" data-trainings-owner="trainings.js"><div class="modal-head"><button class="btn small st-modal-back" data-a="back">Zurück</button><h3>${id?'Unterweisung bearbeiten':'Unterweisung hinzufügen'}</h3><button class="close" data-a="close">Schließen</button></div><div class="modal-body"><div class="form-grid"><div class="field"><label>Unterweisungs-ID</label><input id="enumber" value="${E(t.trainingNumber)}" readonly></div><div class="field"><label>Code</label><input id="ei" value="${E(t.icon)}"></div><div class="field"><label>Version</label><input id="ev" value="${E(t.version)}"></div><div class="field"><label>Kategorie</label><select id="ec">${Object.keys(seed.categories).map(c=>`<option value="${E(c)}" ${t.category===c?'selected':''}>${E(cn(c))}</option>`).join('')}</select></div><div class="field"><label>Wiederholung (Monate)</label><input id="em" type="number" min="1" value="${Number(t.months)||12}"></div><label><input id="ea" type="checkbox" ${t.active!==false?'checked':''}> Aktiv</label></div><h4>Zugeordnete Tätigkeiten</h4><div class="role-grid">${Object.keys(seed.roles).map(r=>`<label><input class="er" type="checkbox" value="${E(r)}" ${(t.roles||[]).includes(r)?'checked':''}> ${E(rn(r))}</label>`).join('')}</div><h4>Sprachfassungen</h4>${L.map(l=>`<details class="lang-block" ${l==='de'?'open':''}><summary>${E(N[l]||l)}</summary><div class="field"><label>Titel</label><input id="et-${E(l)}" value="${E(t.title?.[l]||'')}"><label>Beschreibung</label><textarea id="ed-${E(l)}" rows="3">${E(t.description?.[l]||'')}</textarea></div></details>`).join('')}</div><div class="modal-foot">${id?`<button class="btn" data-training-action="toggle-active" data-id="${E(id)}">${t.active===false?'Aktivieren':'Archivieren'}</button><button class="btn danger" data-training-action="delete" data-id="${E(id)}">Löschen</button>`:''}<button class="btn" data-a="close">Abbrechen</button><button class="btn primary" data-training-action="save" data-id="${E(id)}">Speichern</button></div></div></div>`}
function toast(x){const e=document.querySelector('#toast');if(!e)return;e.textContent=x;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function eligibleEmployee(t){return seed.employees.find(e=>t?.active!==false&&Array.isArray(t?.roles)&&t.roles.some(r=>r==='all'||r===e[4]))||seed.employees[0]}
function saveTraining(id){let x=id?api.catalog.find(t=>t.id===id):{id:'custom-'+Date.now(),trainingNumber:document.querySelector('#enumber')?.value||api.nextTrainingNumber(),custom:true,title:{},description:{},slides:{},questions:{}};if(!x)return;x.trainingNumber=x.trainingNumber||document.querySelector('#enumber')?.value||api.nextTrainingNumber();x.icon=(document.querySelector('#ei')?.value||'').trim().toUpperCase().slice(0,3)||'NE';x.version=document.querySelector('#ev')?.value||'1.0';x.category=document.querySelector('#ec')?.value||'general';x.months=Math.max(1,+document.querySelector('#em')?.value||12);x.active=Boolean(document.querySelector('#ea')?.checked);x.roles=[...document.querySelectorAll('.er:checked')].map(n=>n.value);if(!x.roles.length)x.roles=['all'];L.forEach(l=>{const title=document.querySelector('#et-'+l)?.value.trim()||x.title?.de||'Neue Unterweisung',description=document.querySelector('#ed-'+l)?.value.trim()||x.description?.de||'';x.title=x.title||{};x.description=x.description||{};x.slides=x.slides||{};x.title[l]=title;x.description[l]=description;x.slides[l]=x.slides[l]?.length?x.slides[l]:[[title,[description,'Betriebliche Anweisung beachten','Bei Unsicherheit nachfragen']]]});if(!id)api.catalog.push(x);api.ensureTrainingNumbers();api.persist();api.state.m=null;api.render()}
function copyTraining(id){const src=api.catalog.find(t=>t.id===id);if(!src)return;const x=structuredClone(src);x.id='copy-'+Date.now();x.trainingNumber=api.nextTrainingNumber();x.custom=true;L.forEach(l=>{if(x.title?.[l])x.title[l]+=' – Kopie'});api.catalog.push(x);api.persist();api.pushHistory?.();api.state.m={t:'edit',id:x.id};api.render()}
function deleteTraining(id){const x=api.catalog.find(t=>t.id===id);if(!x)return;if(x.custom&&!api.records.some(r=>r.trainingId===id))api.replaceData({catalog:api.catalog.filter(t=>t.id!==id)});else{x.active=false;api.persist()}api.state.m=null;api.render()}
function toggleActive(id){const x=api.catalog.find(t=>t.id===id);if(!x)return;x.active=!x.active;api.persist();api.state.m=null;api.render()}
function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({catalog:api.catalog,records:api.records},null,2)],{type:'application/json'}));a.download='safetrack-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importData(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!Array.isArray(d.catalog))throw Error('Ungültige Datei');api.replaceData({catalog:d.catalog,records:Array.isArray(d.records)?d.records:api.records});api.render()}catch(e){toast(e.message)}};r.readAsText(file)}
function setCategoryOpen(el,body,open){el.setAttribute('aria-expanded',String(open));if(!body)return;body.hidden=!open;body.style.display=open?'grid':'none'}function toggleCategory(el){const body=document.getElementById(el.getAttribute('aria-controls')||''),open=el.getAttribute('aria-expanded')==='true';setCategoryOpen(el,body,!open)}
document.addEventListener('click',e=>{const b=e.target.closest?.('[data-training-action]');if(!b)return;const a=b.dataset.trainingAction,id=b.dataset.id||'';if(a==='toggle-category'){e.preventDefault();toggleCategory(b);return}if(a==='edit'){api.pushHistory?.();api.state.m={t:'edit',id};api.render();return}if(a==='copy'){copyTraining(id);return}if(a==='start'){const t=api.catalog.find(x=>x.id===id);if(!t)return;const emp=eligibleEmployee(t);api.pushHistory?.();api.state.m={t:'session',e:emp[1],id:t.id};api.render();return}if(a==='toggle-active'){toggleActive(id);return}if(a==='delete'){deleteTraining(id);return}if(a==='save'){saveTraining(id);return}if(a==='export'){exportData();return}if(a==='import'){document.querySelector('#file')?.click();return}if(a==='reset'&&confirm('Testdaten zurücksetzen?')){api.replaceData({catalog:structuredClone(seed.trainings),records:[]});api.render()}},true);
document.addEventListener('keydown',e=>{const b=e.target.closest?.('[data-training-action="toggle-category"]');if(!b||!['Enter',' '].includes(e.key))return;e.preventDefault();toggleCategory(b)},true);
document.addEventListener('input',e=>{if(api.state.page!=='trainings'||!e.target.matches?.('#fs'))return;api.state.f.s=e.target.value;api.render()},true);
document.addEventListener('change',e=>{if(api.state.page!=='trainings')return;if(e.target.matches?.('#fc')){api.state.f.c=e.target.value;api.render();return}if(e.target.matches?.('#fr')){api.state.f.r=e.target.value;api.render();return}if(e.target.matches?.('#fa')){api.state.f.a=e.target.value;api.render();return}if(e.target.matches?.('#file')){const file=e.target.files?.[0];e.target.value='';importData(file)}},true);
window.__SafeTrackTrainings={owner:'trainings.js',renderCatalog,renderEditModal,filtered};
if(api.state.page==='trainings'||api.state.m?.t==='edit')api.render();
})();