import { router, json, error, db, storage, ai } from '@appdeploy/sdk';

type Participant={name:string;pnr:string;role:string};
type DocumentRecord={documentId:string;fingerprint:string;clientToken:string;trainingKey:string;trainingId:string;trainingName:string;version:string;date:string;participants:Participant[];instructor:string;instructorPersonnel:string;pageCount:number;status:string;statusLabel:string;preparedAt:string;updatedAt:string;snapshotPath?:string;printedAt?:string;signedPath?:string;signedName?:string;signedMime?:string;uploadId?:string;autoCheck?:Record<string,unknown>;completedAt?:string};
type UploadRecord={filename:string;mimeType:string;size:number;path:string;status:string;statusLabel:string;createdAt:string;updatedAt:string;analyses:Array<Record<string,unknown>>;qrIds:string[];matchedDocumentId?:string;autoCheck?:Record<string,unknown>};
type StorageWriteItem={path:string;content:string;contentType:string};

const DOCS='documents_v021',UPLOADS='uploads_v021',COMPLETIONS='completions_v021',COUNTERS='counters_v021';
const now=()=>new Date().toISOString();
const delay=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
const normalizePnr=(v:unknown)=>{const s=String(v??'').trim();const m=s.match(/(?:PNr\.?[-\s]*|P[-\s]*)(\d{3,8})/i);return m?`PNr-${m[1]}`:s};
const unique=(xs:string[])=>[...new Set(xs.filter(Boolean))];
const normalizeDocId=(v:unknown)=>{const m=String(v??'').toUpperCase().match(/ST-DOC-\d{4}-\d{6}/);return m?.[0]||''};
const normalizeTraining=(v:unknown)=>{const m=String(v??'').toUpperCase().match(/ST-UW-\d{3}/);return m?.[0]||String(v??'').trim()};
const stripId=<T extends Record<string,unknown>>(x:T)=>{const {id,...rest}=x;return rest};

async function writeStorage(items:StorageWriteItem[],attempts=2){for(let attempt=0;attempt<attempts;attempt++){try{const result=await storage.write(items);if(result.every(Boolean))return true}catch{}if(attempt+1<attempts)await delay(500*(attempt+1))}return false}
async function listAll<T extends Record<string,unknown>>(table:string){let nextToken:string|undefined;const out:Array<T&{id:string}>=[];do{const r=await db.list<T>(table,nextToken?{nextToken}:{});out.push(...r.items);nextToken=r.nextToken}while(nextToken);return out}
async function findDocument(publicId:string){const items=await listAll<DocumentRecord>(DOCS);return items.find(x=>x.documentId===publicId)||null}
async function updateDocument(item:DocumentRecord&{id:string},patch:Partial<DocumentRecord>){const record={...stripId(item),...patch,updatedAt:now()};const [ok]=await db.update(DOCS,[{id:item.id,record}]);if(!ok)throw new Error('Document update failed');return{...record,id:item.id}}
async function findUpload(id:string){const [item]=await db.get<UploadRecord>(UPLOADS,[id]);return item?{...item,id}:null}
async function updateUpload(item:UploadRecord&{id:string},patch:Partial<UploadRecord>){const record={...stripId(item),...patch,updatedAt:now()};const [ok]=await db.update(UPLOADS,[{id:item.id,record}]);if(!ok)throw new Error('Upload update failed');return{...record,id:item.id}}
async function nextDocumentId(){const year=new Date().getFullYear();const items=await listAll<Record<string,unknown>>(COUNTERS);const current=items.find(x=>x.key===`documents-${year}`);let value=1;if(current){value=Number(current.value||0)+1;const [ok]=await db.update(COUNTERS,[{id:current.id,record:{key:`documents-${year}`,value}}]);if(!ok)throw new Error('Counter update failed')}else{const [id]=await db.add(COUNTERS,[{key:`documents-${year}`,value}]);if(!id)throw new Error('Counter create failed')}return`ST-DOC-${year}-${String(value).padStart(6,'0')}`}

function parsePageLabel(v:unknown){const s=String(v??'').trim();const m=s.match(/(?:Seite\s*)?(\d{1,3})\s*(?:\/|von)\s*(\d{1,3})/i);if(!m)return null;return{number:Number(m[1]),total:Number(m[2]),raw:s}}
function extractStructured(data:unknown){const x=(data&&typeof data==='object'?data:{}) as Record<string,unknown>;const legacy=Array.isArray(x.pageLabels)?x.pageLabels.map(v=>String(v)):[];const pageLabel=String(x.pageLabel??legacy[0]??'').trim();return{documentId:normalizeDocId(x.documentId),trainingId:normalizeTraining(x.trainingId),version:String(x.version??'').trim(),pnrs:unique(Array.isArray(x.personnelNumbers)?x.personnelNumbers.map(normalizePnr):[]),pageLabel,signaturesLikelyPresent:Boolean(x.signaturesLikelyPresent)}}
function mergeAnalyses(analyses:Array<Record<string,unknown>>,qrIds:string[]){const pages=analyses.map((a,i)=>{const parsed=extractStructured(a.data);const pageQrIds=unique((Array.isArray(a.qrIds)?a.qrIds:[]).map(normalizeDocId));return{pageIndex:Number(a.pageIndex??a.pageOffset??i),...parsed,qrIds:pageQrIds,page:parsePageLabel(parsed.pageLabel)}}).sort((a,b)=>a.pageIndex-b.pageIndex);const ocrIds=unique(pages.map(x=>x.documentId));const qr=unique([...qrIds.map(normalizeDocId),...pages.flatMap(x=>x.qrIds)]);return{pages,ocrIds,qrIds:qr,trainingIds:unique(pages.map(x=>x.trainingId)),versions:unique(pages.map(x=>x.version)),pnrs:unique(pages.flatMap(x=>x.pnrs)),signaturesLikelyPresent:pages.some(x=>x.signaturesLikelyPresent)}}
function candidateDocumentId(merged:ReturnType<typeof mergeAnalyses>){const counts=new Map<string,number>();for(const p of merged.pages){for(const id of unique([...p.qrIds,p.documentId]))counts.set(id,(counts.get(id)||0)+1)}const ranked=[...counts.entries()].sort((a,b)=>b[1]-a[1]);if(!ranked.length)return'';if(ranked.length>1&&ranked[0][1]===ranked[1][1])return'';return ranked[0][0]}
function strictPageCheck(doc:DocumentRecord,merged:ReturnType<typeof mergeAnalyses>){const expectedCount=Math.max(1,Number(doc.pageCount)||1),receivedCount=merged.pages.length,errors:string[]=[],recognized:number[]=[],unreadablePages:number[]=[],foreignPages:number[]=[],duplicatePages:number[]=[],wrongTotals:number[]=[],qrFailures:number[]=[],ocrFailures:number[]=[];for(const p of merged.pages){const physical=p.pageIndex+1;const qrOk=p.qrIds.length===1&&p.qrIds[0]===doc.documentId;if(!qrOk){qrFailures.push(physical);if(p.qrIds.some(id=>id&&id!==doc.documentId))foreignPages.push(physical);errors.push(p.qrIds.length?`Seite ${physical}: QR-Dokument-ID stimmt nicht mit ${doc.documentId} überein.`:`Seite ${physical}: QR-Dokument-ID konnte nicht eindeutig gelesen werden.`)}const ocrOk=p.documentId===doc.documentId;if(!ocrOk){ocrFailures.push(physical);if(p.documentId&&p.documentId!==doc.documentId)foreignPages.push(physical);errors.push(p.documentId?`Seite ${physical}: gedruckte Dokument-ID ${p.documentId} gehört nicht zu ${doc.documentId}.`:`Seite ${physical}: gedruckte Dokument-ID konnte nicht eindeutig gelesen werden.`)}if(!p.page){unreadablePages.push(physical);errors.push(`Seite ${physical}: Seitenangabe x/y konnte nicht eindeutig gelesen werden.`);continue}if(p.page.total!==expectedCount){wrongTotals.push(physical);errors.push(`Seite ${physical}: Seitenangabe ${p.page.number}/${p.page.total} erwartet */${expectedCount}.`)}if(p.page.number<1||p.page.number>expectedCount){errors.push(`Seite ${physical}: Seitenzahl ${p.page.number}/${p.page.total} liegt außerhalb des erwarteten Bereichs.`)}else recognized.push(p.page.number)}if(receivedCount!==expectedCount)errors.push(`Dokument unvollständig: ${receivedCount}/${expectedCount} Seiten wurden hochgeladen.`);const counts=new Map<number,number>();for(const n of recognized)counts.set(n,(counts.get(n)||0)+1);for(const [n,c] of counts)if(c>1){duplicatePages.push(n);errors.push(`Seite ${n}/${expectedCount} ist ${c}× vorhanden.`)}const missingPages=[];for(let n=1;n<=expectedCount;n++)if(!counts.has(n)){missingPages.push(n);errors.push(`Dokument unvollständig – Seite ${n}/${expectedCount} fehlt.`)}const uniqueForeign=unique(foreignPages.map(String)).map(Number),ok=errors.length===0;return{ok,expectedCount,receivedCount,recognizedPages:[...counts.keys()].sort((a,b)=>a-b),missingPages,duplicatePages,foreignPages:uniqueForeign,unreadablePages,wrongTotals,qrFailures,ocrFailures,errors}}
function compareDocument(doc:DocumentRecord,merged:ReturnType<typeof mergeAnalyses>){const qrId=merged.qrIds.length===1?merged.qrIds[0]:'';const ocrId=merged.ocrIds.length===1?merged.ocrIds[0]:'';const idConflict=Boolean(qrId&&ocrId&&qrId!==ocrId);const trainingMatch=!merged.trainingIds.length||merged.trainingIds.includes(doc.trainingId);const versionMatch=!merged.versions.length||merged.versions.some(v=>v.replace(/^v/i,'')===String(doc.version).replace(/^v/i,''));const expected=new Set(doc.participants.map(p=>normalizePnr(p.pnr)));const detected=new Set(merged.pnrs.map(normalizePnr));const matched=[...expected].filter(p=>detected.has(p));const participantRatio=expected.size?matched.length/expected.size:1;const pageCheck=strictPageCheck(doc,merged);let score=50+(trainingMatch?15:0)+(versionMatch?10:0)+Math.round(participantRatio*25);if(idConflict||!pageCheck.ok)score=Math.min(score,40);score=Math.max(0,Math.min(100,score));const warnings:string[]=[];if(idConflict)warnings.push('QR- und OCR-Dokument-ID stimmen nicht überein.');if(!trainingMatch)warnings.push('Unterweisungs-ID weicht ab.');if(!versionMatch)warnings.push('Version weicht ab.');if(participantRatio<1)warnings.push(`${matched.length}/${expected.size} erwartete PNr. wurden erkannt.`);if(!merged.signaturesLikelyPresent)warnings.push('Unterschriften konnten nicht sicher erkannt werden.');warnings.push(...pageCheck.errors);return{score,qrId,ocrId,idConflict,trainingMatch,versionMatch,expectedPnrs:[...expected],detectedPnrs:[...detected],matchedPnrs:matched,participantRatio,signaturesLikelyPresent:merged.signaturesLikelyPresent,pageCheck,warnings,canComplete:!idConflict&&pageCheck.ok}}

export const handler=router({
 'GET /api/_healthcheck':[async()=>json({message:'Success',version:'SafeTrack v0.22'})],
 'GET /api/documents':[async()=>{const docs=(await listAll<DocumentRecord>(DOCS)).sort((a,b)=>String(b.preparedAt).localeCompare(String(a.preparedAt)));const uploads=(await listAll<UploadRecord>(UPLOADS)).filter(x=>!x.matchedDocumentId).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));return json({documents:docs,unmatchedUploads:uploads})}],
 'POST /api/documents/prepare':[async({body})=>{const input=(body as {documents?:Array<Record<string,unknown>>})?.documents;if(!Array.isArray(input)||!input.length)return error('documents required',400);const existing=await listAll<DocumentRecord>(DOCS);const results=[];for(const raw of input){const clientToken=String(raw.clientToken||''),fingerprint=String(raw.fingerprint||'');let found=existing.find(x=>clientToken&&x.clientToken===clientToken)||existing.find(x=>fingerprint&&x.fingerprint===fingerprint&&x.status!=='done');if(found){results.push({clientToken,documentId:found.documentId});continue}const documentId=await nextDocumentId(),preparedAt=now(),participants=Array.isArray(raw.participants)?raw.participants.map(p=>{const q=p as Record<string,unknown>;return{name:String(q.name||''),pnr:normalizePnr(q.pnr),role:String(q.role||'')}}):[],record:DocumentRecord={documentId,fingerprint,clientToken,trainingKey:String(raw.trainingKey||''),trainingId:normalizeTraining(raw.trainingId),trainingName:String(raw.trainingName||''),version:String(raw.version||''),date:String(raw.date||''),participants,instructor:String(raw.instructor||''),instructorPersonnel:normalizePnr(raw.instructorPersonnel),pageCount:Math.max(1,Number(raw.pageCount||1)),status:'ready',statusLabel:'Druckbereit',preparedAt,updatedAt:preparedAt};const [id]=await db.add(DOCS,[record]);if(!id)return error('document create failed',500);existing.push({...record,id});results.push({clientToken,documentId})}return json({documents:results})}],
 'POST /api/documents/:id/snapshot':[async({params,body})=>{const doc=await findDocument(params.id);if(!doc)return error('document not found',404);const html=String((body as {html?:string})?.html||'');if(!html)return error('html required',400);const path=`snapshots/${doc.documentId}.html`;if(!await writeStorage([{path,content:html,contentType:'text/html; charset=utf-8'}]))return error('snapshot write failed',500);await updateDocument(doc,{snapshotPath:path});return json({ok:true})}],
 'POST /api/documents/:id/printed':[async({params})=>{const doc=await findDocument(params.id);if(!doc)return error('document not found',404);return json({document:await updateDocument(doc,{status:'printed',statusLabel:'Gedruckt – Rückupload ausstehend',printedAt:now()})})}],
 'GET /api/documents/:id':[async({params})=>{const doc=await findDocument(params.id);return doc?json({document:doc}):error('document not found',404)}],
 'GET /api/documents/:id/snapshot-url':[async({params})=>{const doc=await findDocument(params.id);if(!doc?.snapshotPath)return error('snapshot not found',404);const [u]=await storage.url([doc.snapshotPath]);return json({url:u.url})}],
 'GET /api/documents/:id/file-url':[async({params})=>{const doc=await findDocument(params.id);if(!doc?.signedPath)return error('signed file not found',404);const [u]=await storage.url([doc.signedPath]);return json({url:u.url})}],
 'POST /api/uploads/store':[async({body})=>{const b=(body||{}) as Record<string,unknown>,filename=String(b.filename||'document'),mimeType=String(b.mimeType||'application/octet-stream'),size=Number(b.size||0),content=String(b.content||'');if(!content)return error('content required',400);if(size>20*1024*1024)return error('file exceeds 20 MB',413);const createdAt=now(),[id]=await db.add(UPLOADS,[{filename,mimeType,size,path:'',status:'processing',statusLabel:'Automatische Prüfung läuft',createdAt,updatedAt:createdAt,analyses:[],qrIds:[]}]);if(!id)return error('upload create failed',500);const safe=filename.replace(/[^a-zA-Z0-9._-]+/g,'_'),path=`signed/${id}/${safe}`;if(!await writeStorage([{path,content,contentType:mimeType}]))return error('file write failed',500);const item=await findUpload(id);if(!item)return error('upload missing',500);await updateUpload(item,{path});return json({uploadId:id})}],
 'POST /api/uploads/:id/analyze':[async({params,body})=>{const upload=await findUpload(params.id);if(!upload)return error('upload not found',404);const b=(body||{}) as {images?:Array<{data:string;mimeType:string}>;qrIds?:string[];pageOffset?:number};if(!Array.isArray(b.images)||!b.images.length)return error('images required',400);if(b.images.length>5)return error('max 5 images per OCR batch',400);const pageSchema={type:'object',properties:{documentId:{type:'string'},trainingId:{type:'string'},version:{type:'string'},personnelNumbers:{type:'array',items:{type:'string'}},pageLabel:{type:'string'},signaturesLikelyPresent:{type:'boolean'}},required:['documentId','trainingId','version','personnelNumbers','pageLabel','signaturesLikelyPresent']},schema={type:'object',properties:{pages:{type:'array',items:pageSchema}},required:['pages']};const result=await ai.ocr({images:b.images,prompt:'Analyze each SafeTrack Schulungsbestätigung image separately. Return exactly one pages[] item per input image, in the same order. For every page read the printed human-readable ST-DOC identifier, Unterweisungs-ID, version, every PNr., the printed page label in x/y form such as Seite 2/7, and whether handwritten signatures are visibly present. Never merge pages. Use empty strings or arrays when a value is not readable and do not invent values.',schema,thinkingMode:'FAST',maxRetries:2,maxTokens:5000,temperature:0});const payload=(result.data&&typeof result.data==='object'?result.data:{}) as Record<string,unknown>,pageData=Array.isArray(payload.pages)?payload.pages:[],offset=Math.max(0,Number(b.pageOffset||0)),analyses=[...(upload.analyses||[])];for(let i=0;i<b.images.length;i++){const raw=pageData[i],data=(raw&&typeof raw==='object'?raw:{}) as Record<string,unknown>,qr=normalizeDocId(Array.isArray(b.qrIds)?b.qrIds[i]:'' );analyses.push({pageIndex:offset+i,data,qrIds:qr?[qr]:[],text:result.text,attempts:result.attempts})}const qrIds=unique([...(upload.qrIds||[]),...(Array.isArray(b.qrIds)?b.qrIds.map(normalizeDocId):[])]);await updateUpload(upload,{analyses,qrIds});return json({ok:true,analysis:payload,pageCount:analyses.length})}],
 'POST /api/uploads/:id/finalize':[async({params})=>{const upload=await findUpload(params.id);if(!upload)return error('upload not found',404);const merged=mergeAnalyses(upload.analyses||[],upload.qrIds||[]),detectedId=candidateDocumentId(merged),doc=detectedId?await findDocument(detectedId):null;if(!doc){const reason=!detectedId?'Keine eindeutige Dokument-ID erkannt.':'Dokument-ID ist im SafeTrack-Register nicht vorhanden.',autoCheck={score:0,qrId:'',ocrId:'',warnings:[reason],canComplete:false,pageCheck:{ok:false,errors:[reason]}};return json({matched:false,upload:await updateUpload(upload,{status:'unmatched',statusLabel:'Nicht zugeordnet – manuelle Prüfung erforderlich',autoCheck})})}const autoCheck=compareDocument(doc,merged),critical=(autoCheck.pageCheck as {ok?:boolean})?.ok===false,statusLabel=critical?'Kritische Seitenabweichung – Korrektur erforderlich':'Prüfung durch Führungskraft erforderlich',updatedUpload=await updateUpload(upload,{status:'review_required',statusLabel,matchedDocumentId:doc.documentId,autoCheck}),updatedDoc=await updateDocument(doc,{status:'review_required',statusLabel,signedPath:upload.path,signedName:upload.filename,signedMime:upload.mimeType,uploadId:upload.id,autoCheck});return json({matched:true,document:updatedDoc,upload:updatedUpload})}],
 'POST /api/documents/:id/complete':[async({params})=>{const doc=await findDocument(params.id);if(!doc)return error('document not found',404);if(doc.status!=='review_required'||!doc.signedPath)return error('document is not ready for review completion',409);const check=(doc.autoCheck||{}) as Record<string,unknown>;if(check.idConflict===true||check.canComplete===false)return error('critical document validation conflict requires correction',409);const existing=await listAll<Record<string,unknown>>(COMPLETIONS),created=[];for(const p of doc.participants){if(existing.some(x=>x.documentId===doc.documentId&&x.employeeId===p.pnr))continue;const completedAt=now(),record={documentId:doc.documentId,employeeId:p.pnr,employeeName:p.name,role:p.role,trainingKey:doc.trainingKey,trainingId:doc.trainingId,trainingName:doc.trainingName,version:doc.version,date:doc.date,instructor:doc.instructor,instructorPersonnel:doc.instructorPersonnel,signedPath:doc.signedPath,completedAt},[id]=await db.add(COMPLETIONS,[record]);if(id)created.push({...record,id})}return json({document:await updateDocument(doc,{status:'done',statusLabel:'Abgeschlossen – Mitarbeitenden zugeordnet',completedAt:now()}),completions:created})}],
 'GET /api/employees/:pnr/completions':[async({params})=>{const pnr=normalizePnr(params.pnr),all=await listAll<Record<string,unknown>>(COMPLETIONS),items=all.filter(x=>normalizePnr(x.employeeId)===pnr).sort((a,b)=>String(b.completedAt||'').localeCompare(String(a.completedAt||'')));return json({completions:items})}]
});
