import { router, json, error, db, storage, ai } from '@appdeploy/sdk';

type Participant={name:string;pnr:string;role:string};
type DocumentRecord={documentId:string;fingerprint:string;clientToken:string;trainingKey:string;trainingId:string;trainingName:string;version:string;date:string;participants:Participant[];instructor:string;instructorPersonnel:string;pageCount:number;status:string;statusLabel:string;preparedAt:string;updatedAt:string;snapshotPath?:string;printedAt?:string;signedPath?:string;signedName?:string;signedMime?:string;uploadId?:string;autoCheck?:Record<string,unknown>;completedAt?:string};
type UploadRecord={filename:string;mimeType:string;size:number;path:string;status:string;statusLabel:string;createdAt:string;updatedAt:string;analyses:Array<Record<string,unknown>>;qrIds:string[];matchedDocumentId?:string;autoCheck?:Record<string,unknown>};
type StorageWriteItem={path:string;content:string;contentType?:string};

const DOCS='documents_v021',UPLOADS='uploads_v021',COMPLETIONS='completions_v021',COUNTERS='counters_v021';
const now=()=>new Date().toISOString();
const delay=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
const normalizePnr=(v:unknown)=>{const s=String(v??'').trim();const m=s.match(/(?:PNr\.?[-\s]*|P[-\s]*)(\d{3,8})/i);return m?`PNr-${m[1]}`:s};
const unique=(xs:string[])=>[...new Set(xs.filter(Boolean))];
const normalizeDocId=(v:unknown)=>{const m=String(v??'').toUpperCase().match(/ST-DOC-\d{4}-\d{6}/);return m?.[0]||''};
const normalizeTraining=(v:unknown)=>{const m=String(v??'').toUpperCase().match(/ST-UW-\d{3}/);return m?.[0]||String(v??'').trim()};
const stripId=<T extends Record<string,unknown>>(x:T)=>{const {id,...rest}=x;return rest};

async function writeStorage(items:StorageWriteItem[],attempts=2){for(let attempt=0;attempt<attempts;attempt++){try{const result=await storage.write(items);if(result.every(Boolean))return true}catch{}if(attempt+1<attempts)await delay(500*(attempt+1))}return false}
async function listAll<T extends Record<string,unknown>>(table:string){let nextToken: string|undefined;const out:Array<T&{id:string}>=[];do{const r=await db.list<T>(table,nextToken?{nextToken}:{ });out.push(...r.items);nextToken=r.nextToken}while(nextToken);return out}
async function findDocument(publicId:string){const items=await listAll<DocumentRecord>(DOCS);return items.find(x=>x.documentId===publicId)||null}
async function updateDocument(item:DocumentRecord&{id:string},patch:Partial<DocumentRecord>){const record={...stripId(item),...patch,updatedAt:now()};const [ok]=await db.update(DOCS,[{id:item.id,record}]);if(!ok)throw new Error('Document update failed');return {...record,id:item.id}}
async function findUpload(id:string){const [item]=await db.get<UploadRecord>(UPLOADS,[id]);return item?{...item,id}:null}
async function updateUpload(item:UploadRecord&{id:string},patch:Partial<UploadRecord>){const record={...stripId(item),...patch,updatedAt:now()};const [ok]=await db.update(UPLOADS,[{id:item.id,record}]);if(!ok)throw new Error('Upload update failed');return {...record,id:item.id}}
async function nextDocumentId(){const year=new Date().getFullYear();const items=await listAll<Record<string,unknown>>(COUNTERS);const current=items.find(x=>x.key===`documents-${year}`);let value=1;if(current){value=Number(current.value||0)+1;const [ok]=await db.update(COUNTERS,[{id:current.id,record:{key:`documents-${year}`,value}}]);if(!ok)throw new Error('Counter update failed')}else{const [id]=await db.add(COUNTERS,[{key:`documents-${year}`,value}]);if(!id)throw new Error('Counter create failed')}return`ST-DOC-${year}-${String(value).padStart(6,'0')}`}

function extractStructured(data:unknown){const x=(data&&typeof data==='object'?data:{}) as Record<string,unknown>;return{documentId:normalizeDocId(x.documentId),trainingId:normalizeTraining(x.trainingId),version:String(x.version??'').trim(),pnrs:unique(Array.isArray(x.personnelNumbers)?x.personnelNumbers.map(normalizePnr):[]),pageLabels:Array.isArray(x.pageLabels)?x.pageLabels.map(v=>String(v)):[],signaturesLikelyPresent:Boolean(x.signaturesLikelyPresent)}}
function mergeAnalyses(analyses:Array<Record<string,unknown>>,qrIds:string[]){const parsed=analyses.map(a=>extractStructured(a.data));const ocrIds=unique(parsed.map(x=>x.documentId));const qr=unique(qrIds.map(normalizeDocId));return{ocrIds,qrIds:qr,trainingIds:unique(parsed.map(x=>x.trainingId)),versions:unique(parsed.map(x=>x.version)),pnrs:unique(parsed.flatMap(x=>x.pnrs)),pageLabels:unique(parsed.flatMap(x=>x.pageLabels)),signaturesLikelyPresent:parsed.some(x=>x.signaturesLikelyPresent)}}
function compareDocument(doc:DocumentRecord,merged:ReturnType<typeof mergeAnalyses>){const qrId=merged.qrIds.length===1?merged.qrIds[0]:'';const ocrId=merged.ocrIds.length===1?merged.ocrIds[0]:'';const idConflict=Boolean(qrId&&ocrId&&qrId!==ocrId);const trainingMatch=!merged.trainingIds.length||merged.trainingIds.includes(doc.trainingId);const versionMatch=!merged.versions.length||merged.versions.some(v=>v.replace(/^v/i,'')===String(doc.version).replace(/^v/i,''));const expected=new Set(doc.participants.map(p=>normalizePnr(p.pnr)));const detected=new Set(merged.pnrs.map(normalizePnr));const matched=[...expected].filter(p=>detected.has(p));const participantRatio=expected.size?matched.length/expected.size:1;let score=50+(trainingMatch?15:0)+(versionMatch?10:0)+Math.round(participantRatio*25);if(idConflict)score=Math.min(score,45);score=Math.max(0,Math.min(100,score));const warnings:string[]=[];if(idConflict)warnings.push('QR- und OCR-Dokument-ID stimmen nicht überein.');if(!trainingMatch)warnings.push('Unterweisungs-ID weicht ab.');if(!versionMatch)warnings.push('Version weicht ab.');if(participantRatio<1)warnings.push(`${matched.length}/${expected.size} erwartete PNr. wurden erkannt.`);if(!merged.signaturesLikelyPresent)warnings.push('Unterschriften konnten nicht sicher erkannt werden.');return{score,qrId,ocrId,idConflict,trainingMatch,versionMatch,expectedPnrs:[...expected],detectedPnrs:[...detected],matchedPnrs:matched,participantRatio,signaturesLikelyPresent:merged.signaturesLikelyPresent,warnings,canComplete:!idConflict}}

export const handler=router({
 'GET /api/_healthcheck':[async()=>json({message:'Success',version:'SafeTrack v0.21'})],
 'GET /api/documents':[async()=>{const docs=(await listAll<DocumentRecord>(DOCS)).sort((a,b)=>String(b.preparedAt).localeCompare(String(a.preparedAt)));const uploads=(await listAll<UploadRecord>(UPLOADS)).filter(x=>!x.matchedDocumentId).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));return json({documents:docs,unmatchedUploads:uploads})}],
 'POST /api/documents/prepare':[async({body})=>{const input=(body as {documents?:Array<Record<string,unknown>>})?.documents;if(!Array.isArray(input)||!input.length)return error('documents required',400);const existing=await listAll<DocumentRecord>(DOCS);const results=[];for(const raw of input){const clientToken=String(raw.clientToken||'');const fingerprint=String(raw.fingerprint||'');let found=existing.find(x=>clientToken&&x.clientToken===clientToken)||existing.find(x=>fingerprint&&x.fingerprint===fingerprint&&x.status!=='done');if(found){results.push({clientToken,documentId:found.documentId});continue}const documentId=await nextDocumentId();const preparedAt=now();const participants=Array.isArray(raw.participants)?raw.participants.map(p=>{const q=p as Record<string,unknown>;return{name:String(q.name||''),pnr:normalizePnr(q.pnr),role:String(q.role||'')}}):[];const record:DocumentRecord={documentId,fingerprint,clientToken,trainingKey:String(raw.trainingKey||''),trainingId:normalizeTraining(raw.trainingId),trainingName:String(raw.trainingName||''),version:String(raw.version||''),date:String(raw.date||''),participants,instructor:String(raw.instructor||''),instructorPersonnel:normalizePnr(raw.instructorPersonnel),pageCount:Number(raw.pageCount||1),status:'ready',statusLabel:'Druckbereit',preparedAt,updatedAt:preparedAt};const [id]=await db.add(DOCS,[record]);if(!id)return error('document create failed',500);existing.push({...record,id});results.push({clientToken,documentId})}return json({documents:results})}],
 'POST /api/documents/:id/snapshot':[async({params,body})=>{const doc=await findDocument(params.id);if(!doc)return error('document not found',404);const html=String((body as {html?:string})?.html||'');if(!html)return error('html required',400);const path=`snapshots/${doc.documentId}.html`;if(!await writeStorage([{path,content:html,contentType:'text/html; charset=utf-8'}]))return error('snapshot write failed',500);await updateDocument(doc,{snapshotPath:path});return json({ok:true})}],
 'POST /api/documents/:id/printed':[async({params})=>{const doc=await findDocument(params.id);if(!doc)return error('document not found',404);const printedAt=now();const updated=await updateDocument(doc,{status:'printed',statusLabel:'Gedruckt – Rückupload ausstehend',printedAt});return json({document:updated})}],
 'GET /api/documents/:id':[async({params})=>{const doc=await findDocument(params.id);if(!doc)return error('document not found',404);return json({document:doc})}],
 'GET /api/documents/:id/snapshot-url':[async({params})=>{const doc=await findDocument(params.id);if(!doc?.snapshotPath)return error('snapshot not found',404);const [u]=await storage.url([doc.snapshotPath]);return json({url:u.url})}],
 'GET /api/documents/:id/file-url':[async({params})=>{const doc=await findDocument(params.id);if(!doc?.signedPath)return error('signed file not found',404);const [u]=await storage.url([doc.signedPath]);return json({url:u.url})}],
 'POST /api/uploads/store':[async({body})=>{const b=(body||{}) as Record<string,unknown>;const filename=String(b.filename||'document');const mimeType=String(b.mimeType||'application/octet-stream');const size=Number(b.size||0);const content=String(b.content||'');if(!content)return error('content required',400);const createdAt=now();const [id]=await db.add(UPLOADS,[{filename,mimeType,size,path:'',status:'processing',statusLabel:'Automatische Prüfung läuft',createdAt,updatedAt:createdAt,analyses:[],qrIds:[]}]);if(!id)return error('upload create failed',500);const safe=filename.replace(/[^a-zA-Z0-9._-]+/g,'_');const path=`signed/${id}/${safe}`;if(!await writeStorage([{path,content,contentType:mimeType}]))return error('file write failed',500);const item=await findUpload(id);if(!item)return error('upload missing',500);await updateUpload(item,{path});return json({uploadId:id})}],
 'POST /api/uploads/:id/analyze':[async({params,body})=>{const upload=await findUpload(params.id);if(!upload)return error('upload not found',404);const b=(body||{}) as {images?:Array<{data:string;mimeType:string}>;qrIds?:string[];pageOffset?:number};if(!Array.isArray(b.images)||!b.images.length)return error('images required',400);const schema={type:'object',properties:{documentId:{type:'string'},trainingId:{type:'string'},version:{type:'string'},personnelNumbers:{type:'array',items:{type:'string'}},pageLabels:{type:'array',items:{type:'string'}},signaturesLikelyPresent:{type:'boolean'}},required:['documentId','trainingId','version','personnelNumbers','pageLabels','signaturesLikelyPresent']};const result=await ai.ocr({images:b.images,prompt:'Analyze this signed SafeTrack Schulungsbestätigung. Read the printed human-readable ST-DOC identifier, Unterweisungs-ID, version, every personnel number in canonical or near-canonical form, page labels, and whether handwritten signatures are visibly present. Use empty strings/arrays when a field is absent. Do not invent values.',schema,thinkingMode:'FAST',maxRetries:2,maxTokens:3000,temperature:0});const analyses=[...(upload.analyses||[]),{pageOffset:Number(b.pageOffset||0),data:result.data||{},text:result.text,attempts:result.attempts}];const qrIds=unique([...(upload.qrIds||[]),...(Array.isArray(b.qrIds)?b.qrIds:[])]);await updateUpload(upload,{analyses,qrIds});return json({ok:true,analysis:result.data||{}})}],
 'POST /api/uploads/:id/finalize':[async({params})=>{const upload=await findUpload(params.id);if(!upload)return error('upload not found',404);const merged=mergeAnalyses(upload.analyses||[],upload.qrIds||[]);const qrId=merged.qrIds.length===1?merged.qrIds[0]:'';const ocrId=merged.ocrIds.length===1?merged.ocrIds[0]:'';const detectedId=qrId||ocrId;const doc=detectedId?await findDocument(detectedId):null;if(!doc){const reason=!detectedId?'Keine eindeutige Dokument-ID erkannt.':'Dokument-ID ist im SafeTrack-Register nicht vorhanden.';const autoCheck={score:0,qrId,ocrId,warnings:[reason],canComplete:false};const updated=await updateUpload(upload,{status:'unmatched',statusLabel:'Nicht zugeordnet – manuelle Prüfung erforderlich',autoCheck});return json({matched:false,upload:updated})}const autoCheck=compareDocument(doc,merged);const statusLabel='Prüfung durch Führungskraft erforderlich';const updatedUpload=await updateUpload(upload,{status:'review_required',statusLabel,matchedDocumentId:doc.documentId,autoCheck});const updatedDoc=await updateDocument(doc,{status:'review_required',statusLabel,signedPath:upload.path,signedName:upload.filename,signedMime:upload.mimeType,uploadId:upload.id,autoCheck});return json({matched:true,document:updatedDoc,upload:updatedUpload})}],
 'POST /api/documents/:id/complete':[async({params})=>{const doc=await findDocument(params.id);if(!doc)return error('document not found',404);if(doc.status!=='review_required'||!doc.signedPath)return error('document is not ready for review completion',409);const check=(doc.autoCheck||{}) as Record<string,unknown>;if(check.idConflict===true||check.canComplete===false)return error('critical identifier conflict requires correction',409);const existing=await listAll<Record<string,unknown>>(COMPLETIONS);const created=[];for(const p of doc.participants){if(existing.some(x=>x.documentId===doc.documentId&&x.employeeId===p.pnr))continue;const completedAt=now();const record={documentId:doc.documentId,employeeId:p.pnr,employeeName:p.name,role:p.role,trainingKey:doc.trainingKey,trainingId:doc.trainingId,trainingName:doc.trainingName,version:doc.version,date:doc.date,instructor:doc.instructor,instructorPersonnel:doc.instructorPersonnel,signedPath:doc.signedPath,completedAt};const [id]=await db.add(COMPLETIONS,[record]);if(id)created.push({...record,id})}const completedAt=now();const updated=await updateDocument(doc,{status:'done',statusLabel:'Abgeschlossen – Mitarbeitenden zugeordnet',completedAt});return json({document:updated,completions:created})}],
 'GET /api/employees/:pnr/completions':[async({params})=>{const pnr=normalizePnr(params.pnr);const all=await listAll<Record<string,unknown>>(COMPLETIONS);const items=all.filter(x=>normalizePnr(x.employeeId)===pnr).sort((a,b)=>String(b.completedAt||'').localeCompare(String(a.completedAt||'')));return json({completions:items})}]
});
