import { router, json, error, db, storage, ai } from '@appdeploy/sdk';

type Participant={name:string;pnr:string;role:string};
type Receipt={id:string;uploadId:string;uploadPageIndex:number;filename:string;pagePath:string;qrToken:string;ocrDocumentId:string;ocrPageNumber:number;ocrPageTotal:number;trainingId:string;version:string;pnrs:string[];signaturesLikelyPresent:boolean;qrMatch:boolean;ocrDocMatch:boolean;pageMatch:boolean;trainingMatch:boolean;versionMatch:boolean;pnrMatch:boolean;hardConflict:boolean;receivedAt:string};
type PageRecord={documentId:string;pageToken:string;pageNumber:number;totalPages:number;expectedPnrs:string[];status:string;receipts:Receipt[];selectedReceiptId?:string;manualConfirmed?:boolean;originalPath?:string;updatedAt:string};
type DocumentRecord={documentId:string;fingerprint:string;clientToken:string;trainingKey:string;trainingId:string;trainingName:string;version:string;date:string;participants:Participant[];instructor:string;instructorPersonnel:string;pageCount:number;status:string;statusLabel:string;preparedAt:string;updatedAt:string;snapshotPath?:string;printedAt?:string;completedAt?:string};
type UploadRecord={filename:string;mimeType:string;size:number;pageCount:number;status:string;statusLabel:string;createdAt:string;updatedAt:string;matchedDocumentIds:string[];unmatchedPages:Array<Record<string,unknown>>};
type StorageWriteItem={path:string;content:string;contentType:string};
const DOCS='documents_v023',PAGES='pages_v023',UPLOADS='uploads_v023',COMPLETIONS='completions_v023',COUNTERS='counters_v023';
const now=()=>new Date().toISOString();const delay=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const normalizePnr=(v:unknown)=>{const s=String(v??'').trim(),m=s.match(/(?:PNr\.?[-\s]*|P[-\s]*)(\d{3,8})/i);return m?`PNr-${m[1]}`:s};
const normalizeDocId=(v:unknown)=>{const m=String(v??'').toUpperCase().match(/ST-DOC-\d{4}-\d{6}/);return m?.[0]||''};
const normalizePageToken=(v:unknown)=>{const m=String(v??'').trim().match(/STPG-[0-9a-f-]{20,}/i);return m?.[0]||''};
const normalizeTraining=(v:unknown)=>{const m=String(v??'').toUpperCase().match(/ST-UW-\d{3}/);return m?.[0]||String(v??'').trim()};
const unique=<T>(xs:T[])=>[...new Set(xs.filter(Boolean))];
const stripId=<T extends Record<string,unknown>>(x:T)=>{const {id,...rest}=x;return rest};
const parsePageLabel=(v:unknown)=>{const s=String(v??'').trim(),m=s.match(/(?:Seite\s*)?(\d{1,3})\s*(?:\/|von)\s*(\d{1,3})/i);return m?{number:Number(m[1]),total:Number(m[2]),raw:s}:null};
async function writeStorage(items:StorageWriteItem[],attempts=2){for(let a=0;a<attempts;a++){try{const r=await storage.write(items);if(r.every(Boolean))return true}catch{}if(a+1<attempts)await delay(500*(a+1))}return false}
async function listAll<T extends Record<string,unknown>>(table:string){let nextToken:string|undefined;const out:Array<T&{id:string}>=[];do{const r=await db.list<T>(table,nextToken?{nextToken}:{});out.push(...r.items);nextToken=r.nextToken}while(nextToken);return out}
async function findDocument(documentId:string){return(await listAll<DocumentRecord>(DOCS)).find(x=>x.documentId===documentId)||null}
async function documentPages(documentId:string){return(await listAll<PageRecord>(PAGES)).filter(x=>x.documentId===documentId).sort((a,b)=>a.pageNumber-b.pageNumber)}
async function findPageToken(pageToken:string){return(await listAll<PageRecord>(PAGES)).find(x=>x.pageToken===pageToken)||null}
async function updateDocument(item:DocumentRecord&{id:string},patch:Partial<DocumentRecord>){const record={...stripId(item),...patch,updatedAt:now()};const[ok]=await db.update(DOCS,[{id:item.id,record}]);if(!ok)throw new Error('Document update failed');return{...record,id:item.id}}
async function updatePage(item:PageRecord&{id:string},patch:Partial<PageRecord>){const record={...stripId(item),...patch,updatedAt:now()};const[ok]=await db.update(PAGES,[{id:item.id,record}]);if(!ok)throw new Error('Page update failed');return{...record,id:item.id}}
async function findUpload(id:string){const[item]=await db.get<UploadRecord>(UPLOADS,[id]);return item?{...item,id}:null}
async function updateUpload(item:UploadRecord&{id:string},patch:Partial<UploadRecord>){const record={...stripId(item),...patch,updatedAt:now()};const[ok]=await db.update(UPLOADS,[{id:item.id,record}]);if(!ok)throw new Error('Upload update failed');return{...record,id:item.id}}
async function nextDocumentId(){const year=new Date().getFullYear(),items=await listAll<Record<string,unknown>>(COUNTERS),key=`documents-${year}`,current=items.find(x=>x.key===key);let value=1;if(current){value=Number(current.value||0)+1;const[ok]=await db.update(COUNTERS,[{id:current.id,record:{key,value}}]);if(!ok)throw new Error('Counter update failed')}else{const[id]=await db.add(COUNTERS,[{key,value}]);if(!id)throw new Error('Counter create failed')}return`ST-DOC-${year}-${String(value).padStart(6,'0')}`}
const newPageToken=()=>`STPG-${crypto.randomUUID()}`;
function expectedSubset(expected:string[],detected:string[]){const set=new Set(detected.map(normalizePnr));return expected.every(x=>set.has(normalizePnr(x)))}
function pageSummary(page:PageRecord&{id?:string}){return{pageToken:page.pageToken,pageNumber:page.pageNumber,totalPages:page.totalPages,expectedPnrs:page.expectedPnrs,status:page.status,receiptCount:page.receipts?.length||0,selectedReceiptId:page.selectedReceiptId||'',manualConfirmed:Boolean(page.manualConfirmed),hasOriginal:Boolean(page.originalPath),receipts:(page.receipts||[]).map(r=>({id:r.id,filename:r.filename,uploadPageIndex:r.uploadPageIndex,qrMatch:r.qrMatch,ocrDocMatch:r.ocrDocMatch,pageMatch:r.pageMatch,trainingMatch:r.trainingMatch,versionMatch:r.versionMatch,pnrMatch:r.pnrMatch,signaturesLikelyPresent:r.signaturesLikelyPresent,hardConflict:r.hardConflict,receivedAt:r.receivedAt}))}}
function aggregate(doc:DocumentRecord,pages:Array<PageRecord&{id:string}>){const received=pages.filter(p=>(p.receipts?.length||0)>0),verified=pages.filter(p=>p.status==='verified'),missing=pages.filter(p=>(p.receipts?.length||0)===0).map(p=>p.pageNumber),review=pages.filter(p=>p.status==='review').map(p=>p.pageNumber),duplicate=pages.filter(p=>p.status==='duplicate').map(p=>p.pageNumber),conflict=pages.filter(p=>p.status==='conflict').map(p=>p.pageNumber),complete=pages.length===doc.pageCount&&verified.length===doc.pageCount;let status=doc.status,statusLabel=doc.statusLabel;if(doc.status!=='done'){if(complete){status='review_required';statusLabel='Vollständig – Prüfung durch Führungskraft erforderlich'}else if(conflict.length||duplicate.length||review.length){status='page_review';statusLabel='Seitenprüfung erforderlich'}else if(received.length){status='partial';statusLabel=`Teilweise eingegangen – ${received.length}/${doc.pageCount} Seiten`}else if(doc.printedAt){status='printed';statusLabel='Gedruckt – Rückupload ausstehend'}else{status='ready';statusLabel='Druckbereit'}}return{status,statusLabel,progress:{expected:doc.pageCount,received:received.length,verified:verified.length,missing,review,duplicate,conflict,complete}}}
async function refreshDocument(documentId:string){const doc=await findDocument(documentId);if(!doc)return null;const pages=await documentPages(documentId),agg=aggregate(doc,pages);if(doc.status!==agg.status||doc.statusLabel!==agg.statusLabel)return updateDocument(doc,{status:agg.status,statusLabel:agg.statusLabel});return doc}
function structuredPages(data:unknown,count:number){const x=(data&&typeof data==='object'?data:{})as Record<string,unknown>,raw=Array.isArray(x.pages)?x.pages:[];return Array.from({length:count},(_,i)=>{const q=(raw[i]&&typeof raw[i]==='object'?raw[i]:{})as Record<string,unknown>,label=parsePageLabel(q.pageLabel);return{documentId:normalizeDocId(q.documentId),trainingId:normalizeTraining(q.trainingId),version:String(q.version??'').trim(),pnrs:unique(Array.isArray(q.personnelNumbers)?q.personnelNumbers.map(normalizePnr):[]),pageLabel:String(q.pageLabel??''),pageNumber:label?.number||0,pageTotal:label?.total||0,signaturesLikelyPresent:Boolean(q.signaturesLikelyPresent)}})}
async function attachReceipt(upload:UploadRecord&{id:string},image:{data:string;mimeType:string},globalIndex:number,qrRaw:string,ocr:ReturnType<typeof structuredPages>[number]){const qrToken=normalizePageToken(qrRaw);let target=qrToken?await findPageToken(qrToken):null;if(!target&&ocr.documentId&&ocr.pageNumber)target=(await documentPages(ocr.documentId)).find(p=>p.pageNumber===ocr.pageNumber&&p.totalPages===ocr.pageTotal)||null;const safe=upload.filename.replace(/[^a-zA-Z0-9._-]+/g,'_'),pagePath=`page-receipts/${upload.id}/${String(globalIndex+1).padStart(3,'0')}-${safe}.jpg`;if(!await writeStorage([{path:pagePath,content:image.data,contentType:image.mimeType}]))throw new Error('page image write failed');if(!target)return{matched:false,unmatched:{uploadPageIndex:globalIndex+1,filename:upload.filename,pagePath,qrToken,ocrDocumentId:ocr.documentId,pageLabel:ocr.pageLabel,reason:'Keine eindeutige Zuordnung zu einer erwarteten Seite.'}};const doc=await findDocument(target.documentId);if(!doc)return{matched:false,unmatched:{uploadPageIndex:globalIndex+1,filename:upload.filename,pagePath,qrToken,ocrDocumentId:ocr.documentId,pageLabel:ocr.pageLabel,reason:'Zieldokument nicht gefunden.'}};const qrMatch=Boolean(qrToken)&&qrToken===target.pageToken,ocrDocMatch=ocr.documentId===target.documentId,pageMatch=ocr.pageNumber===target.pageNumber&&ocr.pageTotal===target.totalPages,trainingMatch=ocr.trainingId===doc.trainingId,versionMatch=ocr.version.replace(/^v/i,'')===String(doc.version).replace(/^v/i,''),pnrMatch=expectedSubset(target.expectedPnrs,ocr.pnrs),hardConflict=Boolean((qrToken&&qrToken!==target.pageToken)||(ocr.documentId&&ocr.documentId!==target.documentId)||(ocr.pageNumber&&(ocr.pageNumber!==target.pageNumber||ocr.pageTotal!==target.totalPages)));const receipt:Receipt={id:crypto.randomUUID(),uploadId:upload.id,uploadPageIndex:globalIndex+1,filename:upload.filename,pagePath,qrToken,ocrDocumentId:ocr.documentId,ocrPageNumber:ocr.pageNumber,ocrPageTotal:ocr.pageTotal,trainingId:ocr.trainingId,version:ocr.version,pnrs:ocr.pnrs,signaturesLikelyPresent:ocr.signaturesLikelyPresent,qrMatch,ocrDocMatch,pageMatch,trainingMatch,versionMatch,pnrMatch,hardConflict,receivedAt:now()},receipts=[...(target.receipts||[]),receipt];let status='review',selectedReceiptId='';if(receipts.length>1)status='duplicate';else if(hardConflict)status='conflict';else if(qrMatch&&ocrDocMatch&&pageMatch&&trainingMatch&&versionMatch&&pnrMatch&&ocr.signaturesLikelyPresent){status='verified';selectedReceiptId=receipt.id}const updated=await updatePage(target,{receipts,status,selectedReceiptId:selectedReceiptId||undefined,manualConfirmed:false});await refreshDocument(target.documentId);return{matched:true,documentId:target.documentId,page:pageSummary(updated),receipt}}
async function selectedPageUrls(documentId:string,pnr=''){const all=await documentPages(documentId),wanted=pnr?all.filter(p=>p.expectedPnrs.map(normalizePnr).includes(normalizePnr(pnr))):all,pages=pnr&&wanted.length?wanted:all,out=[];for(const p of pages){const selected=(p.receipts||[]).find(r=>r.id===p.selectedReceiptId);if(!selected){out.push({...pageSummary(p),url:''});continue}const[u]=await storage.url([selected.pagePath]);out.push({...pageSummary(p),url:u.url})}return{pages:out,filteredByPnr:Boolean(pnr&&wanted.length),requestedPnr:pnr}}
async function reviewPayload(page:PageRecord&{id:string}){const doc=await findDocument(page.documentId);if(!doc)return null;let originalUrl='',originalMode='none';if(page.originalPath){const[u]=await storage.url([page.originalPath]);originalUrl=u.url;originalMode='page'}else if(doc.snapshotPath){const[u]=await storage.url([doc.snapshotPath]);originalUrl=u.url;originalMode='document'}const paths=(page.receipts||[]).map(r=>r.pagePath),urls=paths.length?await storage.url(paths):[],byPath=new Map(urls.map(u=>[u.path,u.url]));return{documentId:doc.documentId,trainingId:doc.trainingId,version:doc.version,page:pageSummary(page),originalUrl,originalMode,receipts:(page.receipts||[]).map(r=>({...r,url:byPath.get(r.pagePath)||''}))}}
export const handler=router({
'GET /api/_healthcheck':[async()=>json({message:'Success',version:'SafeTrack v0.24'})],
'GET /api/documents':[async()=>{const docs=(await listAll<DocumentRecord>(DOCS)).sort((a,b)=>String(b.preparedAt).localeCompare(String(a.preparedAt))),items=[];for(const d of docs){const pages=await documentPages(d.documentId),agg=aggregate(d,pages);items.push({...d,status:agg.status,statusLabel:agg.statusLabel,progress:agg.progress,pages:pages.map(pageSummary)})}const uploads=(await listAll<UploadRecord>(UPLOADS)).filter(x=>(x.unmatchedPages||[]).length);return json({documents:items,unmatchedUploads:uploads})}],
'POST /api/documents/prepare':[async({body})=>{const input=(body as {documents?:Array<Record<string,unknown>>})?.documents;if(!Array.isArray(input)||!input.length)return error('documents required',400);const existing=await listAll<DocumentRecord>(DOCS),results=[];for(const raw of input){const clientToken=String(raw.clientToken||''),fingerprint=String(raw.fingerprint||''),found=existing.find(x=>clientToken&&x.clientToken===clientToken)||existing.find(x=>fingerprint&&x.fingerprint===fingerprint&&x.status!=='done');if(found){const pages=await documentPages(found.documentId);results.push({clientToken,documentId:found.documentId,pages:pages.map(p=>({pageNumber:p.pageNumber,totalPages:p.totalPages,pageToken:p.pageToken}))});continue}const documentId=await nextDocumentId(),preparedAt=now(),participants=Array.isArray(raw.participants)?raw.participants.map(p=>{const q=p as Record<string,unknown>;return{name:String(q.name||''),pnr:normalizePnr(q.pnr),role:String(q.role||'')}}):[],pageCount=Math.max(1,Math.min(30,Number(raw.pageCount||1))),record:DocumentRecord={documentId,fingerprint,clientToken,trainingKey:String(raw.trainingKey||''),trainingId:normalizeTraining(raw.trainingId),trainingName:String(raw.trainingName||''),version:String(raw.version||''),date:String(raw.date||''),participants,instructor:String(raw.instructor||''),instructorPersonnel:normalizePnr(raw.instructorPersonnel),pageCount,status:'ready',statusLabel:'Druckbereit',preparedAt,updatedAt:preparedAt};const[docDbId]=await db.add(DOCS,[record]);if(!docDbId)return error('document create failed',500);const rawPages=Array.isArray(raw.pages)?raw.pages:[],pageDefs=Array.from({length:pageCount},(_,i)=>{const q=(rawPages[i]&&typeof rawPages[i]==='object'?rawPages[i]:{})as Record<string,unknown>;return{documentId,pageToken:newPageToken(),pageNumber:i+1,totalPages:pageCount,expectedPnrs:unique(Array.isArray(q.expectedPnrs)?q.expectedPnrs.map(normalizePnr):participants.map(p=>p.pnr)),status:'expected',receipts:[],updatedAt:preparedAt}}),ids=await db.add(PAGES,pageDefs);if(ids.some(x=>!x))return error('page create failed',500);existing.push({...record,id:docDbId});results.push({clientToken,documentId,pages:pageDefs.map(p=>({pageNumber:p.pageNumber,totalPages:p.totalPages,pageToken:p.pageToken}))})}return json({documents:results})}],
'POST /api/documents/:id/snapshot':[async({params,body})=>{const doc=await findDocument(params.id);if(!doc)return error('document not found',404);const b=(body||{})as{html?:string;pages?:Array<{pageNumber?:number;html?:string}>},html=String(b.html||'');if(!html)return error('html required',400);const fullPath=`snapshots-v024/${doc.documentId}/document.html`,pageInputs=Array.isArray(b.pages)?b.pages:[],writes:StorageWriteItem[]=[{path:fullPath,content:html,contentType:'text/html; charset=utf-8'}],pagePaths=new Map<number,string>();for(const p of pageInputs){const n=Number(p.pageNumber||0),h=String(p.html||'');if(!n||!h)continue;const path=`snapshots-v024/${doc.documentId}/page-${String(n).padStart(3,'0')}.html`;pagePaths.set(n,path);writes.push({path,content:h,contentType:'text/html; charset=utf-8'})}if(!await writeStorage(writes))return error('snapshot write failed',500);await updateDocument(doc,{snapshotPath:fullPath});if(pagePaths.size){const pages=await documentPages(doc.documentId);for(const p of pages){const path=pagePaths.get(p.pageNumber);if(path)await updatePage(p,{originalPath:path})}}return json({ok:true,pageSnapshots:pagePaths.size})}],
'POST /api/documents/:id/printed':[async({params})=>{const doc=await findDocument(params.id);if(!doc)return error('document not found',404);return json({document:await updateDocument(doc,{status:'printed',statusLabel:'Gedruckt – Rückupload ausstehend',printedAt:now()})})}],
'GET /api/documents/:id':[async({params})=>{const doc=await findDocument(params.id);if(!doc)return error('document not found',404);const pages=await documentPages(doc.documentId),agg=aggregate(doc,pages);return json({document:{...doc,status:agg.status,statusLabel:agg.statusLabel,progress:agg.progress,pages:pages.map(pageSummary)}})}],
'GET /api/documents/:id/snapshot-url':[async({params})=>{const doc=await findDocument(params.id);if(!doc?.snapshotPath)return error('snapshot not found',404);const[u]=await storage.url([doc.snapshotPath]);return json({url:u.url})}],
'GET /api/documents/:id/pages':[async({params,query})=>{const doc=await findDocument(params.id);if(!doc)return error('document not found',404);const r=await selectedPageUrls(doc.documentId,String(query.pnr||''));return json({documentId:doc.documentId,...r})}],
'GET /api/pages/:token/review':[async({params})=>{const page=await findPageToken(params.token);if(!page)return error('page not found',404);const payload=await reviewPayload(page);if(!payload)return error('document not found',404);return json(payload)}],
'POST /api/uploads/store':[async({body})=>{const b=(body||{})as Record<string,unknown>,filename=String(b.filename||'document'),mimeType=String(b.mimeType||'application/octet-stream'),size=Number(b.size||0),pageCount=Math.max(1,Number(b.pageCount||1));if(size>20*1024*1024)return error('file exceeds 20 MB',413);if(pageCount>30)return error('file exceeds 30 pages',413);const createdAt=now(),record:UploadRecord={filename,mimeType,size,pageCount,status:'processing',statusLabel:'Automatische Seitenzuordnung läuft',createdAt,updatedAt:createdAt,matchedDocumentIds:[],unmatchedPages:[]},[id]=await db.add(UPLOADS,[record]);if(!id)return error('upload create failed',500);return json({uploadId:id})}],
'POST /api/uploads/:id/analyze':[async({params,body})=>{const upload=await findUpload(params.id);if(!upload)return error('upload not found',404);const b=(body||{})as{images?:Array<{data:string;mimeType:string}>;qrTokens?:string[];pageOffset?:number};if(!Array.isArray(b.images)||!b.images.length)return error('images required',400);if(b.images.length>5)return error('max 5 images per OCR batch',400);const schema={type:'object',properties:{pages:{type:'array',items:{type:'object',properties:{documentId:{type:'string'},trainingId:{type:'string'},version:{type:'string'},personnelNumbers:{type:'array',items:{type:'string'}},pageLabel:{type:'string'},signaturesLikelyPresent:{type:'boolean'}},required:['documentId','trainingId','version','personnelNumbers','pageLabel','signaturesLikelyPresent']}}},required:['pages']},result=await ai.ocr({images:b.images,prompt:'Analyze each SafeTrack page independently and return one pages[] object per input image in the exact same order. Read the printed ST-DOC identifier, Unterweisungs-ID, version, every PNr., Seite x/y, and whether handwritten signatures are visible. Never merge information across images. Use empty values when unreadable.',schema,thinkingMode:'FAST',maxRetries:2,maxTokens:5000,temperature:0}),parsed=structuredPages(result.data,b.images.length),matchedDocumentIds=new Set(upload.matchedDocumentIds||[]),unmatched=[...(upload.unmatchedPages||[])],pageResults=[];for(let i=0;i<b.images.length;i++){const globalIndex=Number(b.pageOffset||0)+i,attached=await attachReceipt(upload,b.images[i],globalIndex,String(b.qrTokens?.[i]||''),parsed[i]);pageResults.push(attached);if(attached.matched)matchedDocumentIds.add(attached.documentId);else unmatched.push(attached.unmatched)}await updateUpload(upload,{matchedDocumentIds:[...matchedDocumentIds],unmatchedPages:unmatched});return json({ok:true,pages:pageResults})}],
'POST /api/uploads/:id/finalize':[async({params})=>{const upload=await findUpload(params.id);if(!upload)return error('upload not found',404);const docs=[];for(const id of upload.matchedDocumentIds||[]){const d=await refreshDocument(id);if(d){const pages=await documentPages(id),agg=aggregate(d,pages);docs.push({...d,status:agg.status,statusLabel:agg.statusLabel,progress:agg.progress})}}const status=upload.unmatchedPages?.length?'review_required':'processed',statusLabel=upload.unmatchedPages?.length?'Nicht zugeordnete Seiten – manuelle Prüfung erforderlich':'Seiten automatisch zugeordnet',updated=await updateUpload(upload,{status,statusLabel});return json({documents:docs,unmatchedPages:updated.unmatchedPages||[]})}],
'POST /api/pages/:token/confirm':[async({params})=>{const page=await findPageToken(params.token);if(!page)return error('page not found',404);if((page.receipts||[]).length!==1)return error('page requires receipt selection',409);const receipt=page.receipts[0];if(receipt.hardConflict)return error('hard page identity conflict',409);const updated=await updatePage(page,{status:'verified',selectedReceiptId:receipt.id,manualConfirmed:true});await refreshDocument(page.documentId);return json({page:pageSummary(updated)})}],
'POST /api/pages/:token/select':[async({params,body})=>{const page=await findPageToken(params.token);if(!page)return error('page not found',404);const receiptId=String((body as{receiptId?:string})?.receiptId||''),receipt=(page.receipts||[]).find(r=>r.id===receiptId);if(!receipt)return error('receipt not found',404);if(receipt.hardConflict)return error('hard page identity conflict',409);const updated=await updatePage(page,{status:'verified',selectedReceiptId:receipt.id,manualConfirmed:true});await refreshDocument(page.documentId);return json({page:pageSummary(updated)})}],
'POST /api/documents/:id/complete':[async({params})=>{const doc=await findDocument(params.id);if(!doc)return error('document not found',404);const pages=await documentPages(doc.documentId),agg=aggregate(doc,pages);if(!agg.progress.complete)return error('all expected pages must be verified first',409);const existing=await listAll<Record<string,unknown>>(COMPLETIONS),created=[];for(const p of doc.participants){if(existing.some(x=>x.documentId===doc.documentId&&x.employeeId===p.pnr))continue;const completedAt=now(),record={documentId:doc.documentId,employeeId:p.pnr,employeeName:p.name,role:p.role,trainingKey:doc.trainingKey,trainingId:doc.trainingId,trainingName:doc.trainingName,version:doc.version,date:doc.date,instructor:doc.instructor,instructorPersonnel:doc.instructorPersonnel,completedAt},[id]=await db.add(COMPLETIONS,[record]);if(id)created.push({...record,id})}return json({document:await updateDocument(doc,{status:'done',statusLabel:'Abgeschlossen – Mitarbeitenden zugeordnet',completedAt:now()}),completions:created})}],
'GET /api/employees/:pnr/completions':[async({params})=>{const pnr=normalizePnr(params.pnr),all=await listAll<Record<string,unknown>>(COMPLETIONS),items=all.filter(x=>normalizePnr(x.employeeId)===pnr).sort((a,b)=>String(b.completedAt||'').localeCompare(String(a.completedAt||'')));return json({completions:items})}]
});
